// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: manager.proto

package server

import (
	"context"

	"github.com/yanshicheng/kube-nova/application/manager-rpc/internal/logic/managerservice"
	"github.com/yanshicheng/kube-nova/application/manager-rpc/internal/svc"
	"github.com/yanshicheng/kube-nova/application/manager-rpc/pb"
)

type ManagerServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedManagerServiceServer
}

func NewManagerServiceServer(svcCtx *svc.ServiceContext) *ManagerServiceServer {
	return &ManagerServiceServer{
		svcCtx: svcCtx,
	}
}

// //通过 clusterUuid 和 namespace 获取 详情信息
func (s *ManagerServiceServer) GetClusterNsDetail(ctx context.Context, in *pb.GetClusterNsDetailReq) (*pb.GetClusterNsDetailResp, error) {
	l := managerservicelogic.NewGetClusterNsDetailLogic(ctx, s.svcCtx)
	return l.GetClusterNsDetail(in)
}

// 获取某一个集群的所有ns
func (s *ManagerServiceServer) GetClusterNs(ctx context.Context, in *pb.GetClusterNsReq) (*pb.GetClusterNsResp, error) {
	l := managerservicelogic.NewGetClusterNsLogic(ctx, s.svcCtx)
	return l.GetClusterNs(in)
}

// -----------------------告警实例表-----------------------
func (s *ManagerServiceServer) AlertInstancesDel(ctx context.Context, in *pb.DelAlertInstancesReq) (*pb.DelAlertInstancesResp, error) {
	l := managerservicelogic.NewAlertInstancesDelLogic(ctx, s.svcCtx)
	return l.AlertInstancesDel(in)
}

func (s *ManagerServiceServer) AlertInstancesByIdGet(ctx context.Context, in *pb.GetAlertInstancesByIdReq) (*pb.GetAlertInstancesByIdResp, error) {
	l := managerservicelogic.NewAlertInstancesByIdGetLogic(ctx, s.svcCtx)
	return l.AlertInstancesByIdGet(in)
}

func (s *ManagerServiceServer) AlertInstancesSearch(ctx context.Context, in *pb.SearchAlertInstancesReq) (*pb.SearchAlertInstancesResp, error) {
	l := managerservicelogic.NewAlertInstancesSearchLogic(ctx, s.svcCtx)
	return l.AlertInstancesSearch(in)
}

func (s *ManagerServiceServer) AlertInstancesBatchDel(ctx context.Context, in *pb.BatchDelAlertInstancesReq) (*pb.BatchDelAlertInstancesResp, error) {
	l := managerservicelogic.NewAlertInstancesBatchDelLogic(ctx, s.svcCtx)
	return l.AlertInstancesBatchDel(in)
}

// -----------------------告警规则表-----------------------
func (s *ManagerServiceServer) AlertRuleFileAdd(ctx context.Context, in *pb.AddAlertRuleFileReq) (*pb.AddAlertRuleFileResp, error) {
	l := managerservicelogic.NewAlertRuleFileAddLogic(ctx, s.svcCtx)
	return l.AlertRuleFileAdd(in)
}

func (s *ManagerServiceServer) AlertRuleFileUpdate(ctx context.Context, in *pb.UpdateAlertRuleFileReq) (*pb.UpdateAlertRuleFileResp, error) {
	l := managerservicelogic.NewAlertRuleFileUpdateLogic(ctx, s.svcCtx)
	return l.AlertRuleFileUpdate(in)
}

func (s *ManagerServiceServer) AlertRuleFileDel(ctx context.Context, in *pb.DelAlertRuleFileReq) (*pb.DelAlertRuleFileResp, error) {
	l := managerservicelogic.NewAlertRuleFileDelLogic(ctx, s.svcCtx)
	return l.AlertRuleFileDel(in)
}

func (s *ManagerServiceServer) AlertRuleFileGetById(ctx context.Context, in *pb.GetAlertRuleFileByIdReq) (*pb.GetAlertRuleFileByIdResp, error) {
	l := managerservicelogic.NewAlertRuleFileGetByIdLogic(ctx, s.svcCtx)
	return l.AlertRuleFileGetById(in)
}

func (s *ManagerServiceServer) AlertRuleFileSearch(ctx context.Context, in *pb.SearchAlertRuleFileReq) (*pb.SearchAlertRuleFileResp, error) {
	l := managerservicelogic.NewAlertRuleFileSearchLogic(ctx, s.svcCtx)
	return l.AlertRuleFileSearch(in)
}

func (s *ManagerServiceServer) AlertRuleFileList(ctx context.Context, in *pb.ListAlertRuleFileReq) (*pb.ListAlertRuleFileResp, error) {
	l := managerservicelogic.NewAlertRuleFileListLogic(ctx, s.svcCtx)
	return l.AlertRuleFileList(in)
}

// ===================== 告警规则分组表 =====================
func (s *ManagerServiceServer) AlertRuleGroupAdd(ctx context.Context, in *pb.AddAlertRuleGroupReq) (*pb.AddAlertRuleGroupResp, error) {
	l := managerservicelogic.NewAlertRuleGroupAddLogic(ctx, s.svcCtx)
	return l.AlertRuleGroupAdd(in)
}

func (s *ManagerServiceServer) AlertRuleGroupUpdate(ctx context.Context, in *pb.UpdateAlertRuleGroupReq) (*pb.UpdateAlertRuleGroupResp, error) {
	l := managerservicelogic.NewAlertRuleGroupUpdateLogic(ctx, s.svcCtx)
	return l.AlertRuleGroupUpdate(in)
}

func (s *ManagerServiceServer) AlertRuleGroupDel(ctx context.Context, in *pb.DelAlertRuleGroupReq) (*pb.DelAlertRuleGroupResp, error) {
	l := managerservicelogic.NewAlertRuleGroupDelLogic(ctx, s.svcCtx)
	return l.AlertRuleGroupDel(in)
}

func (s *ManagerServiceServer) AlertRuleGroupGetById(ctx context.Context, in *pb.GetAlertRuleGroupByIdReq) (*pb.GetAlertRuleGroupByIdResp, error) {
	l := managerservicelogic.NewAlertRuleGroupGetByIdLogic(ctx, s.svcCtx)
	return l.AlertRuleGroupGetById(in)
}

func (s *ManagerServiceServer) AlertRuleGroupSearch(ctx context.Context, in *pb.SearchAlertRuleGroupReq) (*pb.SearchAlertRuleGroupResp, error) {
	l := managerservicelogic.NewAlertRuleGroupSearchLogic(ctx, s.svcCtx)
	return l.AlertRuleGroupSearch(in)
}

func (s *ManagerServiceServer) AlertRuleGroupList(ctx context.Context, in *pb.ListAlertRuleGroupReq) (*pb.ListAlertRuleGroupResp, error) {
	l := managerservicelogic.NewAlertRuleGroupListLogic(ctx, s.svcCtx)
	return l.AlertRuleGroupList(in)
}

// ===================== 告警规则表 =====================
func (s *ManagerServiceServer) AlertRuleAdd(ctx context.Context, in *pb.AddAlertRuleReq) (*pb.AddAlertRuleResp, error) {
	l := managerservicelogic.NewAlertRuleAddLogic(ctx, s.svcCtx)
	return l.AlertRuleAdd(in)
}

func (s *ManagerServiceServer) AlertRuleUpdate(ctx context.Context, in *pb.UpdateAlertRuleReq) (*pb.UpdateAlertRuleResp, error) {
	l := managerservicelogic.NewAlertRuleUpdateLogic(ctx, s.svcCtx)
	return l.AlertRuleUpdate(in)
}

func (s *ManagerServiceServer) AlertRuleDel(ctx context.Context, in *pb.DelAlertRuleReq) (*pb.DelAlertRuleResp, error) {
	l := managerservicelogic.NewAlertRuleDelLogic(ctx, s.svcCtx)
	return l.AlertRuleDel(in)
}

func (s *ManagerServiceServer) AlertRuleGetById(ctx context.Context, in *pb.GetAlertRuleByIdReq) (*pb.GetAlertRuleByIdResp, error) {
	l := managerservicelogic.NewAlertRuleGetByIdLogic(ctx, s.svcCtx)
	return l.AlertRuleGetById(in)
}

func (s *ManagerServiceServer) AlertRuleSearch(ctx context.Context, in *pb.SearchAlertRuleReq) (*pb.SearchAlertRuleResp, error) {
	l := managerservicelogic.NewAlertRuleSearchLogic(ctx, s.svcCtx)
	return l.AlertRuleSearch(in)
}

func (s *ManagerServiceServer) AlertRuleBatchDel(ctx context.Context, in *pb.BatchDelAlertRuleReq) (*pb.BatchDelAlertRuleResp, error) {
	l := managerservicelogic.NewAlertRuleBatchDelLogic(ctx, s.svcCtx)
	return l.AlertRuleBatchDel(in)
}

// ===================== 导入/导出/部署 =====================
func (s *ManagerServiceServer) AlertRulesBatchImport(ctx context.Context, in *pb.BatchImportAlertRulesReq) (*pb.BatchImportAlertRulesResp, error) {
	l := managerservicelogic.NewAlertRulesBatchImportLogic(ctx, s.svcCtx)
	return l.AlertRulesBatchImport(in)
}

func (s *ManagerServiceServer) AlertRulesBatchExport(ctx context.Context, in *pb.BatchExportAlertRulesReq) (*pb.BatchExportAlertRulesResp, error) {
	l := managerservicelogic.NewAlertRulesBatchExportLogic(ctx, s.svcCtx)
	return l.AlertRulesBatchExport(in)
}

func (s *ManagerServiceServer) AlertRulesDeploy(ctx context.Context, in *pb.DeployAlertRulesReq) (*pb.DeployAlertRulesResp, error) {
	l := managerservicelogic.NewAlertRulesDeployLogic(ctx, s.svcCtx)
	return l.AlertRulesDeploy(in)
}

func (s *ManagerServiceServer) AlertRulesPreviewYaml(ctx context.Context, in *pb.PreviewAlertRulesYamlReq) (*pb.PreviewAlertRulesYamlResp, error) {
	l := managerservicelogic.NewAlertRulesPreviewYamlLogic(ctx, s.svcCtx)
	return l.AlertRulesPreviewYaml(in)
}

func (s *ManagerServiceServer) AlertRulesExportAll(ctx context.Context, in *pb.ExportAllAlertRulesReq) (*pb.ExportAllAlertRulesResp, error) {
	l := managerservicelogic.NewAlertRulesExportAllLogic(ctx, s.svcCtx)
	return l.AlertRulesExportAll(in)
}

func (s *ManagerServiceServer) AlertRulesDeployAll(ctx context.Context, in *pb.DeployAllAlertRulesReq) (*pb.DeployAllAlertRulesResp, error) {
	l := managerservicelogic.NewAlertRulesDeployAllLogic(ctx, s.svcCtx)
	return l.AlertRulesDeployAll(in)
}

// ===================== 树形结构 =====================
func (s *ManagerServiceServer) AlertRuleTreeGet(ctx context.Context, in *pb.GetAlertRuleTreeReq) (*pb.GetAlertRuleTreeResp, error) {
	l := managerservicelogic.NewAlertRuleTreeGetLogic(ctx, s.svcCtx)
	return l.AlertRuleTreeGet(in)
}

// ===================== Alertmanager Webhook =====================
func (s *ManagerServiceServer) ReceiveAlertmanagerWebhook(ctx context.Context, in *pb.ReceiveAlertmanagerWebhookReq) (*pb.ReceiveAlertmanagerWebhookResp, error) {
	l := managerservicelogic.NewReceiveAlertmanagerWebhookLogic(ctx, s.svcCtx)
	return l.ReceiveAlertmanagerWebhook(in)
}

// 获取集群默认域名后缀
func (s *ManagerServiceServer) GetClusterDefaultDomainSuffix(ctx context.Context, in *pb.GetClusterDefaultDomainSuffixReq) (*pb.GetClusterDefaultDomainSuffixResp, error) {
	l := managerservicelogic.NewGetClusterDefaultDomainSuffixLogic(ctx, s.svcCtx)
	return l.GetClusterDefaultDomainSuffix(in)
}

// 获取集群 node or master lb 列表
func (s *ManagerServiceServer) GetClusterLbList(ctx context.Context, in *pb.GetClusterLbListReq) (*pb.GetClusterLbListResp, error) {
	l := managerservicelogic.NewGetClusterLbListLogic(ctx, s.svcCtx)
	return l.GetClusterLbList(in)
}

// 通过集群uuid获取集群认证信息
func (s *ManagerServiceServer) GetClusterAuthInfo(ctx context.Context, in *pb.GetClusterAuthInfoReq) (*pb.GetClusterAuthInfoResp, error) {
	l := managerservicelogic.NewGetClusterAuthInfoLogic(ctx, s.svcCtx)
	return l.GetClusterAuthInfo(in)
}

// 修改集群认证信息
func (s *ManagerServiceServer) ClusterUpdateAuthInfo(ctx context.Context, in *pb.ClusterUpdateAuthInfoReq) (*pb.ClusterUpdateAuthInfoResp, error) {
	l := managerservicelogic.NewClusterUpdateAuthInfoLogic(ctx, s.svcCtx)
	return l.ClusterUpdateAuthInfo(in)
}

// 修改集群图标
func (s *ManagerServiceServer) ClusterUpdateIcon(ctx context.Context, in *pb.ClusterUpdateAvatarReq) (*pb.ClusterUpdateAvatarResp, error) {
	l := managerservicelogic.NewClusterUpdateIconLogic(ctx, s.svcCtx)
	return l.ClusterUpdateIcon(in)
}

// 测试集群连通性
func (s *ManagerServiceServer) ClusterTestConnect(ctx context.Context, in *pb.ClusterTestConnectReq) (*pb.ClusterTestConnectResp, error) {
	l := managerservicelogic.NewClusterTestConnectLogic(ctx, s.svcCtx)
	return l.ClusterTestConnect(in)
}

// 删除集群
func (s *ManagerServiceServer) ClusterDelete(ctx context.Context, in *pb.DeleteClusterReq) (*pb.DeleteClusterResp, error) {
	l := managerservicelogic.NewClusterDeleteLogic(ctx, s.svcCtx)
	return l.ClusterDelete(in)
}

// 修改集群
func (s *ManagerServiceServer) ClusterUpdate(ctx context.Context, in *pb.UpdateClusterReq) (*pb.UpdateClusterResp, error) {
	l := managerservicelogic.NewClusterUpdateLogic(ctx, s.svcCtx)
	return l.ClusterUpdate(in)
}

func (s *ManagerServiceServer) ClusterSearch(ctx context.Context, in *pb.SearchClusterReq) (*pb.SearchClusterResp, error) {
	l := managerservicelogic.NewClusterSearchLogic(ctx, s.svcCtx)
	return l.ClusterSearch(in)
}

func (s *ManagerServiceServer) ClusterAdd(ctx context.Context, in *pb.AddClusterRequest) (*pb.AddClusterResponse, error) {
	l := managerservicelogic.NewClusterAddLogic(ctx, s.svcCtx)
	return l.ClusterAdd(in)
}

// 获取 某一个集群 ingressDomain 列表
func (s *ManagerServiceServer) GetClusterIngressDomainList(ctx context.Context, in *pb.GetClusterDomainListReq) (*pb.GetClusterDomainListResp, error) {
	l := managerservicelogic.NewGetClusterIngressDomainListLogic(ctx, s.svcCtx)
	return l.GetClusterIngressDomainList(in)
}

func (s *ManagerServiceServer) GetClusterNetwork(ctx context.Context, in *pb.GetClusterNetworkReq) (*pb.GetClusterNetworkResp, error) {
	l := managerservicelogic.NewGetClusterNetworkLogic(ctx, s.svcCtx)
	return l.GetClusterNetwork(in)
}

func (s *ManagerServiceServer) UpdateClusterStorageCapacity(ctx context.Context, in *pb.UpdateClusterStorageCapacityReq) (*pb.UpdateClusterStorageCapacityResp, error) {
	l := managerservicelogic.NewUpdateClusterStorageCapacityLogic(ctx, s.svcCtx)
	return l.UpdateClusterStorageCapacity(in)
}

// 获取集群详情
func (s *ManagerServiceServer) ClusterDetail(ctx context.Context, in *pb.ClusterDetailReq) (*pb.ClusterDetailResp, error) {
	l := managerservicelogic.NewClusterDetailLogic(ctx, s.svcCtx)
	return l.ClusterDetail(in)
}

func (s *ManagerServiceServer) ClusterSync(ctx context.Context, in *pb.SyncClusterReq) (*pb.SyncClusterResp, error) {
	l := managerservicelogic.NewClusterSyncLogic(ctx, s.svcCtx)
	return l.ClusterSync(in)
}

func (s *ManagerServiceServer) ClusterAuthInfo(ctx context.Context, in *pb.ClusterAuthInfoReq) (*pb.ClusterAuthInfoResp, error) {
	l := managerservicelogic.NewClusterAuthInfoLogic(ctx, s.svcCtx)
	return l.ClusterAuthInfo(in)
}

// 集群资源
func (s *ManagerServiceServer) ClusterResourceInfo(ctx context.Context, in *pb.ClusterResourceInfoReq) (*pb.ClusterResourceInfoResp, error) {
	l := managerservicelogic.NewClusterResourceInfoLogic(ctx, s.svcCtx)
	return l.ClusterResourceInfo(in)
}

// 同步某一个集群资源
func (s *ManagerServiceServer) ClusterResourceSync(ctx context.Context, in *pb.ClusterResourceSyncReq) (*pb.ClusterResourceSyncResp, error) {
	l := managerservicelogic.NewClusterResourceSyncLogic(ctx, s.svcCtx)
	return l.ClusterResourceSync(in)
}

func (s *ManagerServiceServer) ClusterSyncAll(ctx context.Context, in *pb.ClusterSyncAllReq) (*pb.ClusterSyncAllResp, error) {
	l := managerservicelogic.NewClusterSyncAllLogic(ctx, s.svcCtx)
	return l.ClusterSyncAll(in)
}

// node 相关
func (s *ManagerServiceServer) NodeInfo(ctx context.Context, in *pb.ClusterNodeInfoReq) (*pb.ClusterNodeInfoResp, error) {
	l := managerservicelogic.NewNodeInfoLogic(ctx, s.svcCtx)
	return l.NodeInfo(in)
}

func (s *ManagerServiceServer) NodeDetail(ctx context.Context, in *pb.ClusterNodeDetailReq) (*pb.OnecClusterNodeResp, error) {
	l := managerservicelogic.NewNodeDetailLogic(ctx, s.svcCtx)
	return l.NodeDetail(in)
}

// 获取 node  yaml describe
func (s *ManagerServiceServer) NodeYamlDescribe(ctx context.Context, in *pb.ClusterNodeYamlDescribeReq) (*pb.ClusterNodeYamlDescribeResp, error) {
	l := managerservicelogic.NewNodeYamlDescribeLogic(ctx, s.svcCtx)
	return l.NodeYamlDescribe(in)
}

// labels 相关
func (s *ManagerServiceServer) NodeLabelsList(ctx context.Context, in *pb.ClusterNodeLabelsListReq) (*pb.ClusterNodeLabelsListResp, error) {
	l := managerservicelogic.NewNodeLabelsListLogic(ctx, s.svcCtx)
	return l.NodeLabelsList(in)
}

// 添加 labels
func (s *ManagerServiceServer) NodeAddLabels(ctx context.Context, in *pb.ClusterNodeAddLabelsReq) (*pb.ClusterNodeDisableResp, error) {
	l := managerservicelogic.NewNodeAddLabelsLogic(ctx, s.svcCtx)
	return l.NodeAddLabels(in)
}

// 删除 labels
func (s *ManagerServiceServer) NodeDeleteLabels(ctx context.Context, in *pb.ClusterNodeDeleteLabelsReq) (*pb.ClusterNodeDisableResp, error) {
	l := managerservicelogic.NewNodeDeleteLabelsLogic(ctx, s.svcCtx)
	return l.NodeDeleteLabels(in)
}

// 注解相关
func (s *ManagerServiceServer) NodeAddAnnotations(ctx context.Context, in *pb.ClusterNodeAddAnnotationsReq) (*pb.ClusterNodeAddAnnotationsResp, error) {
	l := managerservicelogic.NewNodeAddAnnotationsLogic(ctx, s.svcCtx)
	return l.NodeAddAnnotations(in)
}

// 删除注解
func (s *ManagerServiceServer) NodeDeleteAnnotations(ctx context.Context, in *pb.ClusterNodeDeleteAnnotationsReq) (*pb.ClusterNodeDeleteAnnotationsResp, error) {
	l := managerservicelogic.NewNodeDeleteAnnotationsLogic(ctx, s.svcCtx)
	return l.NodeDeleteAnnotations(in)
}

// 获取注解列表
func (s *ManagerServiceServer) NodeAnnotationsList(ctx context.Context, in *pb.ClusterNodeAnnotationsListReq) (*pb.ClusterNodeAnnotationsListResp, error) {
	l := managerservicelogic.NewNodeAnnotationsListLogic(ctx, s.svcCtx)
	return l.NodeAnnotationsList(in)
}

// 污点相关
func (s *ManagerServiceServer) NodeDisable(ctx context.Context, in *pb.ClusterNodeDisableReq) (*pb.ClusterNodeDisableResp, error) {
	l := managerservicelogic.NewNodeDisableLogic(ctx, s.svcCtx)
	return l.NodeDisable(in)
}

// 添加污点
func (s *ManagerServiceServer) NodeAddTaint(ctx context.Context, in *pb.ClusterNodeAddTaintReq) (*pb.ClusterNodeAddTaintResp, error) {
	l := managerservicelogic.NewNodeAddTaintLogic(ctx, s.svcCtx)
	return l.NodeAddTaint(in)
}

// 删除污点
func (s *ManagerServiceServer) NodeDeleteTaint(ctx context.Context, in *pb.ClusterNodeDeleteTaintReq) (*pb.ClusterNodeDisableResp, error) {
	l := managerservicelogic.NewNodeDeleteTaintLogic(ctx, s.svcCtx)
	return l.NodeDeleteTaint(in)
}

// 获取污点列表
func (s *ManagerServiceServer) NodeTaintList(ctx context.Context, in *pb.ClusterNodeTaintsListReq) (*pb.ClusterNodeTaintsListResp, error) {
	l := managerservicelogic.NewNodeTaintListLogic(ctx, s.svcCtx)
	return l.NodeTaintList(in)
}

// 驱逐
func (s *ManagerServiceServer) NodeEvict(ctx context.Context, in *pb.ClusterEvictReq) (*pb.ClusterEvictResp, error) {
	l := managerservicelogic.NewNodeEvictLogic(ctx, s.svcCtx)
	return l.NodeEvict(in)
}

// app 相关
func (s *ManagerServiceServer) AppAdd(ctx context.Context, in *pb.AddClusterAppReq) (*pb.AddClusterAppResp, error) {
	l := managerservicelogic.NewAppAddLogic(ctx, s.svcCtx)
	return l.AppAdd(in)
}

// 获取 app 详情信息
func (s *ManagerServiceServer) AppDetail(ctx context.Context, in *pb.ClusterAppDetailReq) (*pb.ClusterAppDetailResp, error) {
	l := managerservicelogic.NewAppDetailLogic(ctx, s.svcCtx)
	return l.AppDetail(in)
}

// 测试中间件是否正常。
func (s *ManagerServiceServer) AppValidate(ctx context.Context, in *pb.ClusterAppValidateReq) (*pb.ClusterAppValidateResp, error) {
	l := managerservicelogic.NewAppValidateLogic(ctx, s.svcCtx)
	return l.AppValidate(in)
}

// 获取某一个集群 app 列表
func (s *ManagerServiceServer) AppOnClusterList(ctx context.Context, in *pb.ClusterAppListReq) (*pb.ClusterAppListResp, error) {
	l := managerservicelogic.NewAppOnClusterListLogic(ctx, s.svcCtx)
	return l.AppOnClusterList(in)
}

// 通过集群以及apptype 获取默认app 的配置信息
func (s *ManagerServiceServer) AppDefaultConfig(ctx context.Context, in *pb.AppDefaultConfigReq) (*pb.AppDefaultConfigResp, error) {
	l := managerservicelogic.NewAppDefaultConfigLogic(ctx, s.svcCtx)
	return l.AppDefaultConfig(in)
}

// -----------------------项目表，记录项目信息-----------------------
func (s *ManagerServiceServer) ProjectAdd(ctx context.Context, in *pb.AddOnecProjectReq) (*pb.AddOnecProjectResp, error) {
	l := managerservicelogic.NewProjectAddLogic(ctx, s.svcCtx)
	return l.ProjectAdd(in)
}

func (s *ManagerServiceServer) ProjectUpdate(ctx context.Context, in *pb.UpdateOnecProjectReq) (*pb.UpdateOnecProjectResp, error) {
	l := managerservicelogic.NewProjectUpdateLogic(ctx, s.svcCtx)
	return l.ProjectUpdate(in)
}

func (s *ManagerServiceServer) ProjectDel(ctx context.Context, in *pb.DelOnecProjectReq) (*pb.DelOnecProjectResp, error) {
	l := managerservicelogic.NewProjectDelLogic(ctx, s.svcCtx)
	return l.ProjectDel(in)
}

func (s *ManagerServiceServer) ProjectGetById(ctx context.Context, in *pb.GetOnecProjectByIdReq) (*pb.GetOnecProjectByIdResp, error) {
	l := managerservicelogic.NewProjectGetByIdLogic(ctx, s.svcCtx)
	return l.ProjectGetById(in)
}

func (s *ManagerServiceServer) ProjectSearch(ctx context.Context, in *pb.SearchOnecProjectReq) (*pb.SearchOnecProjectResp, error) {
	l := managerservicelogic.NewProjectSearchLogic(ctx, s.svcCtx)
	return l.ProjectSearch(in)
}

func (s *ManagerServiceServer) ProjectSync(ctx context.Context, in *pb.ProjectSyncReq) (*pb.ProjectSyncResp, error) {
	l := managerservicelogic.NewProjectSyncLogic(ctx, s.svcCtx)
	return l.ProjectSync(in)
}

// 同步所有项目配额
func (s *ManagerServiceServer) ProjectAllSync(ctx context.Context, in *pb.ProjectQuotaSyncReq) (*pb.ProjectQuotaSyncResp, error) {
	l := managerservicelogic.NewProjectAllSyncLogic(ctx, s.svcCtx)
	return l.ProjectAllSync(in)
}

// -----------------------项目管理员表，关联项目与用户的多对多关系-----------------------
func (s *ManagerServiceServer) ProjectAdminAdd(ctx context.Context, in *pb.AddOnecProjectAdminReq) (*pb.AddOnecProjectAdminResp, error) {
	l := managerservicelogic.NewProjectAdminAddLogic(ctx, s.svcCtx)
	return l.ProjectAdminAdd(in)
}

func (s *ManagerServiceServer) ProjectAdminGetByProjectId(ctx context.Context, in *pb.GetOnecProjectAdminsByProjectIdReq) (*pb.GetOnecProjectAdminsByProjectIdResp, error) {
	l := managerservicelogic.NewProjectAdminGetByProjectIdLogic(ctx, s.svcCtx)
	return l.ProjectAdminGetByProjectId(in)
}

// 通过用户ID查询可用的项目
func (s *ManagerServiceServer) ProjectGetByUserId(ctx context.Context, in *pb.GetOnecProjectsByUserIdReq) (*pb.GetOnecProjectsByUserIdResp, error) {
	l := managerservicelogic.NewProjectGetByUserIdLogic(ctx, s.svcCtx)
	return l.ProjectGetByUserId(in)
}

// -----------------------项目集群配额表，记录项目配额信息-----------------------
func (s *ManagerServiceServer) ProjectClusterAdd(ctx context.Context, in *pb.AddOnecProjectClusterReq) (*pb.AddOnecProjectClusterResp, error) {
	l := managerservicelogic.NewProjectClusterAddLogic(ctx, s.svcCtx)
	return l.ProjectClusterAdd(in)
}

func (s *ManagerServiceServer) ProjectClusterUpdate(ctx context.Context, in *pb.UpdateOnecProjectClusterReq) (*pb.UpdateOnecProjectClusterResp, error) {
	l := managerservicelogic.NewProjectClusterUpdateLogic(ctx, s.svcCtx)
	return l.ProjectClusterUpdate(in)
}

func (s *ManagerServiceServer) ProjectClusterDel(ctx context.Context, in *pb.DelOnecProjectClusterReq) (*pb.DelOnecProjectClusterResp, error) {
	l := managerservicelogic.NewProjectClusterDelLogic(ctx, s.svcCtx)
	return l.ProjectClusterDel(in)
}

func (s *ManagerServiceServer) ProjectClusterGetById(ctx context.Context, in *pb.GetOnecProjectClusterByIdReq) (*pb.GetOnecProjectClusterByIdResp, error) {
	l := managerservicelogic.NewProjectClusterGetByIdLogic(ctx, s.svcCtx)
	return l.ProjectClusterGetById(in)
}

func (s *ManagerServiceServer) ProjectClusterSearch(ctx context.Context, in *pb.SearchOnecProjectClusterReq) (*pb.SearchOnecProjectClusterResp, error) {
	l := managerservicelogic.NewProjectClusterSearchLogic(ctx, s.svcCtx)
	return l.ProjectClusterSearch(in)
}

// 同步项目集群配额 同步就是计算各种资源的 使用量，更新表
func (s *ManagerServiceServer) ProjectClusterSync(ctx context.Context, in *pb.ProjectClusterSyncReq) (*pb.ProjectClusterSyncResp, error) {
	l := managerservicelogic.NewProjectClusterSyncLogic(ctx, s.svcCtx)
	return l.ProjectClusterSync(in)
}

// -----------------------项目工作空间表，记录项目工作空间信息-----------------------
func (s *ManagerServiceServer) ProjectWorkspaceAdd(ctx context.Context, in *pb.AddOnecProjectWorkspaceReq) (*pb.AddOnecProjectWorkspaceResp, error) {
	l := managerservicelogic.NewProjectWorkspaceAddLogic(ctx, s.svcCtx)
	return l.ProjectWorkspaceAdd(in)
}

func (s *ManagerServiceServer) ProjectWorkspaceUpdate(ctx context.Context, in *pb.UpdateOnecProjectWorkspaceReq) (*pb.UpdateOnecProjectWorkspaceResp, error) {
	l := managerservicelogic.NewProjectWorkspaceUpdateLogic(ctx, s.svcCtx)
	return l.ProjectWorkspaceUpdate(in)
}

func (s *ManagerServiceServer) ProjectWorkspaceDel(ctx context.Context, in *pb.DelOnecProjectWorkspaceReq) (*pb.DelOnecProjectWorkspaceResp, error) {
	l := managerservicelogic.NewProjectWorkspaceDelLogic(ctx, s.svcCtx)
	return l.ProjectWorkspaceDel(in)
}

func (s *ManagerServiceServer) ProjectWorkspaceGetById(ctx context.Context, in *pb.GetOnecProjectWorkspaceByIdReq) (*pb.GetOnecProjectWorkspaceByIdResp, error) {
	l := managerservicelogic.NewProjectWorkspaceGetByIdLogic(ctx, s.svcCtx)
	return l.ProjectWorkspaceGetById(in)
}

func (s *ManagerServiceServer) ProjectWorkspaceSearch(ctx context.Context, in *pb.SearchOnecProjectWorkspaceReq) (*pb.SearchOnecProjectWorkspaceResp, error) {
	l := managerservicelogic.NewProjectWorkspaceSearchLogic(ctx, s.svcCtx)
	return l.ProjectWorkspaceSearch(in)
}

func (s *ManagerServiceServer) ProjectWorkspaceSync(ctx context.Context, in *pb.ProjectWorkspaceSyncReq) (*pb.ProjectWorkspaceSyncResp, error) {
	l := managerservicelogic.NewProjectWorkspaceSyncLogic(ctx, s.svcCtx)
	return l.ProjectWorkspaceSync(in)
}

// 项目的应用表相关rpc
func (s *ManagerServiceServer) ApplicationAdd(ctx context.Context, in *pb.AddOnecProjectApplicationReq) (*pb.AddOnecProjectApplicationResp, error) {
	l := managerservicelogic.NewApplicationAddLogic(ctx, s.svcCtx)
	return l.ApplicationAdd(in)
}

func (s *ManagerServiceServer) ApplicationUpdate(ctx context.Context, in *pb.UpdateOnecProjectApplicationReq) (*pb.UpdateOnecProjectApplicationResp, error) {
	l := managerservicelogic.NewApplicationUpdateLogic(ctx, s.svcCtx)
	return l.ApplicationUpdate(in)
}

func (s *ManagerServiceServer) ApplicationDel(ctx context.Context, in *pb.DelOnecProjectApplicationReq) (*pb.DelOnecProjectApplicationResp, error) {
	l := managerservicelogic.NewApplicationDelLogic(ctx, s.svcCtx)
	return l.ApplicationDel(in)
}

func (s *ManagerServiceServer) ApplicationGetById(ctx context.Context, in *pb.GetOnecProjectApplicationByIdReq) (*pb.GetOnecProjectApplicationByIdResp, error) {
	l := managerservicelogic.NewApplicationGetByIdLogic(ctx, s.svcCtx)
	return l.ApplicationGetById(in)
}

func (s *ManagerServiceServer) ApplicationSearch(ctx context.Context, in *pb.SearchOnecProjectApplicationReq) (*pb.SearchOnecProjectApplicationResp, error) {
	l := managerservicelogic.NewApplicationSearchLogic(ctx, s.svcCtx)
	return l.ApplicationSearch(in)
}

// 项目的应用表 版本相关 rpc
func (s *ManagerServiceServer) VersionAdd(ctx context.Context, in *pb.AddOnecProjectVersionReq) (*pb.AddOnecProjectVersionResp, error) {
	l := managerservicelogic.NewVersionAddLogic(ctx, s.svcCtx)
	return l.VersionAdd(in)
}

func (s *ManagerServiceServer) VersionDel(ctx context.Context, in *pb.DelOnecProjectVersionReq) (*pb.DelOnecProjectVersionResp, error) {
	l := managerservicelogic.NewVersionDelLogic(ctx, s.svcCtx)
	return l.VersionDel(in)
}

func (s *ManagerServiceServer) VersionSearch(ctx context.Context, in *pb.SearchOnecProjectVersionReq) (*pb.SearchOnecProjectVersionResp, error) {
	l := managerservicelogic.NewVersionSearchLogic(ctx, s.svcCtx)
	return l.VersionSearch(in)
}

// 获取版本detailinfo
func (s *ManagerServiceServer) VersionDetail(ctx context.Context, in *pb.GetOnecProjectVersionDetailReq) (*pb.GetOnecProjectVersionDetailResp, error) {
	l := managerservicelogic.NewVersionDetailLogic(ctx, s.svcCtx)
	return l.VersionDetail(in)
}

// -----------------------资源操作审计日志表，记录所有资源控制器操作-----------------------
func (s *ManagerServiceServer) ProjectAuditLogAdd(ctx context.Context, in *pb.AddOnecProjectAuditLogReq) (*pb.AddOnecProjectAuditLogResp, error) {
	l := managerservicelogic.NewProjectAuditLogAddLogic(ctx, s.svcCtx)
	return l.ProjectAuditLogAdd(in)
}

func (s *ManagerServiceServer) ProjectAuditLogDel(ctx context.Context, in *pb.DelOnecProjectAuditLogReq) (*pb.DelOnecProjectAuditLogResp, error) {
	l := managerservicelogic.NewProjectAuditLogDelLogic(ctx, s.svcCtx)
	return l.ProjectAuditLogDel(in)
}

func (s *ManagerServiceServer) ProjectAuditLogSearch(ctx context.Context, in *pb.SearchOnecProjectAuditLogReq) (*pb.SearchOnecProjectAuditLogResp, error) {
	l := managerservicelogic.NewProjectAuditLogSearchLogic(ctx, s.svcCtx)
	return l.ProjectAuditLogSearch(in)
}

// 批量删除
func (s *ManagerServiceServer) ProjectAuditLogBatchDel(ctx context.Context, in *pb.BatchDelOnecProjectAuditLogReq) (*pb.BatchDelOnecProjectAuditLogResp, error) {
	l := managerservicelogic.NewProjectAuditLogBatchDelLogic(ctx, s.svcCtx)
	return l.ProjectAuditLogBatchDel(in)
}

// 删除指定天数之前的数据
func (s *ManagerServiceServer) ProjectAuditLogDelBeforeDays(ctx context.Context, in *pb.DelOnecProjectAuditLogBeforeDaysReq) (*pb.DelOnecProjectAuditLogBeforeDaysResp, error) {
	l := managerservicelogic.NewProjectAuditLogDelBeforeDaysLogic(ctx, s.svcCtx)
	return l.ProjectAuditLogDelBeforeDays(in)
}

func (s *ManagerServiceServer) SchedulePlanSave(ctx context.Context, in *pb.SaveSchedulePlanReq) (*pb.SaveSchedulePlanResp, error) {
	l := managerservicelogic.NewSchedulePlanSaveLogic(ctx, s.svcCtx)
	return l.SchedulePlanSave(in)
}

func (s *ManagerServiceServer) SchedulePlanUpdateStatus(ctx context.Context, in *pb.UpdateSchedulePlanStatusReq) (*pb.UpdateSchedulePlanStatusResp, error) {
	l := managerservicelogic.NewSchedulePlanUpdateStatusLogic(ctx, s.svcCtx)
	return l.SchedulePlanUpdateStatus(in)
}

// 迁移相关
func (s *ManagerServiceServer) MigrateWorkspace(ctx context.Context, in *pb.MigrateWorkspaceReq) (*pb.MigrateWorkspaceResp, error) {
	l := managerservicelogic.NewMigrateWorkspaceLogic(ctx, s.svcCtx)
	return l.MigrateWorkspace(in)
}

// 告警仪表盘
func (s *ManagerServiceServer) AlertDashboardOverview(ctx context.Context, in *pb.GetAlertOverviewReq) (*pb.GetAlertOverviewResp, error) {
	l := managerservicelogic.NewAlertDashboardOverviewLogic(ctx, s.svcCtx)
	return l.AlertDashboardOverview(in)
}

// 获取告警级别统计
func (s *ManagerServiceServer) AlertDashboardSeverityStats(ctx context.Context, in *pb.GetAlertSeverityStatsReq) (*pb.GetAlertSeverityStatsResp, error) {
	l := managerservicelogic.NewAlertDashboardSeverityStatsLogic(ctx, s.svcCtx)
	return l.AlertDashboardSeverityStats(in)
}

// 获取告警趋势分析
func (s *ManagerServiceServer) AlertDashboardTrend(ctx context.Context, in *pb.GetAlertTrendReq) (*pb.GetAlertTrendResp, error) {
	l := managerservicelogic.NewAlertDashboardTrendLogic(ctx, s.svcCtx)
	return l.AlertDashboardTrend(in)
}

// 获取告警维度统计
func (s *ManagerServiceServer) AlertDashboardDimensionStats(ctx context.Context, in *pb.GetAlertDimensionStatsReq) (*pb.GetAlertDimensionStatsResp, error) {
	l := managerservicelogic.NewAlertDashboardDimensionStatsLogic(ctx, s.svcCtx)
	return l.AlertDashboardDimensionStats(in)
}

// 获取告警排行榜
func (s *ManagerServiceServer) AlertDashboardTopRanking(ctx context.Context, in *pb.GetAlertTopRankingReq) (*pb.GetAlertTopRankingResp, error) {
	l := managerservicelogic.NewAlertDashboardTopRankingLogic(ctx, s.svcCtx)
	return l.AlertDashboardTopRanking(in)
}

// 获取告警实时状态
func (s *ManagerServiceServer) AlertDashboardRealtimeStatus(ctx context.Context, in *pb.GetAlertRealtimeStatusReq) (*pb.GetAlertRealtimeStatusResp, error) {
	l := managerservicelogic.NewAlertDashboardRealtimeStatusLogic(ctx, s.svcCtx)
	return l.AlertDashboardRealtimeStatus(in)
}

// 获取告警汇总报告
func (s *ManagerServiceServer) AlertDashboardSummaryReport(ctx context.Context, in *pb.GetAlertSummaryReportReq) (*pb.GetAlertSummaryReportResp, error) {
	l := managerservicelogic.NewAlertDashboardSummaryReportLogic(ctx, s.svcCtx)
	return l.AlertDashboardSummaryReport(in)
}

// 集群资源仪表盘
func (s *ManagerServiceServer) GetResourceDashboardSummary(ctx context.Context, in *pb.ResourceDashboardSummaryReq) (*pb.ResourceDashboardSummaryResp, error) {
	l := managerservicelogic.NewGetResourceDashboardSummaryLogic(ctx, s.svcCtx)
	return l.GetResourceDashboardSummary(in)
}

// 获取集群资源排行
func (s *ManagerServiceServer) GetClusterResourceRanking(ctx context.Context, in *pb.ClusterResourceRankingReq) (*pb.ClusterResourceRankingResp, error) {
	l := managerservicelogic.NewGetClusterResourceRankingLogic(ctx, s.svcCtx)
	return l.GetClusterResourceRanking(in)
}

// 获取项目资源排行
func (s *ManagerServiceServer) GetProjectResourceRanking(ctx context.Context, in *pb.ProjectResourceRankingReq) (*pb.ProjectResourceRankingResp, error) {
	l := managerservicelogic.NewGetProjectResourceRankingLogic(ctx, s.svcCtx)
	return l.GetProjectResourceRanking(in)
}

// 获取工作空间资源排行
func (s *ManagerServiceServer) GetWorkspaceResourceRanking(ctx context.Context, in *pb.WorkspaceResourceRankingReq) (*pb.WorkspaceResourceRankingResp, error) {
	l := managerservicelogic.NewGetWorkspaceResourceRankingLogic(ctx, s.svcCtx)
	return l.GetWorkspaceResourceRanking(in)
}

// -----------------------收费配置表-----------------------
func (s *ManagerServiceServer) OnecBillingPriceConfigAdd(ctx context.Context, in *pb.OnecBillingPriceConfigAddReq) (*pb.OnecBillingPriceConfigAddResp, error) {
	l := managerservicelogic.NewOnecBillingPriceConfigAddLogic(ctx, s.svcCtx)
	return l.OnecBillingPriceConfigAdd(in)
}

func (s *ManagerServiceServer) OnecBillingPriceConfigUpdate(ctx context.Context, in *pb.OnecBillingPriceConfigUpdateReq) (*pb.OnecBillingPriceConfigUpdateResp, error) {
	l := managerservicelogic.NewOnecBillingPriceConfigUpdateLogic(ctx, s.svcCtx)
	return l.OnecBillingPriceConfigUpdate(in)
}

func (s *ManagerServiceServer) OnecBillingPriceConfigDel(ctx context.Context, in *pb.OnecBillingPriceConfigDelReq) (*pb.OnecBillingPriceConfigDelResp, error) {
	l := managerservicelogic.NewOnecBillingPriceConfigDelLogic(ctx, s.svcCtx)
	return l.OnecBillingPriceConfigDel(in)
}

func (s *ManagerServiceServer) OnecBillingPriceConfigGetById(ctx context.Context, in *pb.OnecBillingPriceConfigGetByIdReq) (*pb.OnecBillingPriceConfigGetByIdResp, error) {
	l := managerservicelogic.NewOnecBillingPriceConfigGetByIdLogic(ctx, s.svcCtx)
	return l.OnecBillingPriceConfigGetById(in)
}

func (s *ManagerServiceServer) OnecBillingPriceConfigSearch(ctx context.Context, in *pb.OnecBillingPriceConfigSearchReq) (*pb.OnecBillingPriceConfigSearchResp, error) {
	l := managerservicelogic.NewOnecBillingPriceConfigSearchLogic(ctx, s.svcCtx)
	return l.OnecBillingPriceConfigSearch(in)
}

// -----------------------计费配置绑定表-----------------------
func (s *ManagerServiceServer) OnecBillingConfigBindingAdd(ctx context.Context, in *pb.OnecBillingConfigBindingAddReq) (*pb.OnecBillingConfigBindingAddResp, error) {
	l := managerservicelogic.NewOnecBillingConfigBindingAddLogic(ctx, s.svcCtx)
	return l.OnecBillingConfigBindingAdd(in)
}

func (s *ManagerServiceServer) OnecBillingConfigBindingUpdate(ctx context.Context, in *pb.OnecBillingConfigBindingUpdateReq) (*pb.OnecBillingConfigBindingUpdateResp, error) {
	l := managerservicelogic.NewOnecBillingConfigBindingUpdateLogic(ctx, s.svcCtx)
	return l.OnecBillingConfigBindingUpdate(in)
}

func (s *ManagerServiceServer) OnecBillingConfigBindingDel(ctx context.Context, in *pb.OnecBillingConfigBindingDelReq) (*pb.OnecBillingConfigBindingDelResp, error) {
	l := managerservicelogic.NewOnecBillingConfigBindingDelLogic(ctx, s.svcCtx)
	return l.OnecBillingConfigBindingDel(in)
}

func (s *ManagerServiceServer) OnecBillingConfigBindingGet(ctx context.Context, in *pb.OnecBillingConfigBindingGetReq) (*pb.OnecBillingConfigBindingGetResp, error) {
	l := managerservicelogic.NewOnecBillingConfigBindingGetLogic(ctx, s.svcCtx)
	return l.OnecBillingConfigBindingGet(in)
}

// -----------------------账单仪表盘-----------------------
func (s *ManagerServiceServer) OnecBillingDashboardStats(ctx context.Context, in *pb.OnecBillingDashboardStatsReq) (*pb.OnecBillingDashboardStatsResp, error) {
	l := managerservicelogic.NewOnecBillingDashboardStatsLogic(ctx, s.svcCtx)
	return l.OnecBillingDashboardStats(in)
}

func (s *ManagerServiceServer) OnecBillingCostComposition(ctx context.Context, in *pb.OnecBillingCostCompositionReq) (*pb.OnecBillingCostCompositionResp, error) {
	l := managerservicelogic.NewOnecBillingCostCompositionLogic(ctx, s.svcCtx)
	return l.OnecBillingCostComposition(in)
}

func (s *ManagerServiceServer) OnecBillingCostTrend(ctx context.Context, in *pb.OnecBillingCostTrendReq) (*pb.OnecBillingCostTrendResp, error) {
	l := managerservicelogic.NewOnecBillingCostTrendLogic(ctx, s.svcCtx)
	return l.OnecBillingCostTrend(in)
}

func (s *ManagerServiceServer) OnecBillingProjectTop(ctx context.Context, in *pb.OnecBillingProjectTopReq) (*pb.OnecBillingProjectTopResp, error) {
	l := managerservicelogic.NewOnecBillingProjectTopLogic(ctx, s.svcCtx)
	return l.OnecBillingProjectTop(in)
}

func (s *ManagerServiceServer) OnecBillingClusterTop(ctx context.Context, in *pb.OnecBillingClusterTopReq) (*pb.OnecBillingClusterTopResp, error) {
	l := managerservicelogic.NewOnecBillingClusterTopLogic(ctx, s.svcCtx)
	return l.OnecBillingClusterTop(in)
}

// -----------------------账单中心-----------------------
func (s *ManagerServiceServer) OnecBillingStatementSearch(ctx context.Context, in *pb.OnecBillingStatementSearchReq) (*pb.OnecBillingStatementSearchResp, error) {
	l := managerservicelogic.NewOnecBillingStatementSearchLogic(ctx, s.svcCtx)
	return l.OnecBillingStatementSearch(in)
}

func (s *ManagerServiceServer) OnecBillingStatementDel(ctx context.Context, in *pb.OnecBillingStatementDelReq) (*pb.OnecBillingStatementDelResp, error) {
	l := managerservicelogic.NewOnecBillingStatementDelLogic(ctx, s.svcCtx)
	return l.OnecBillingStatementDel(in)
}

func (s *ManagerServiceServer) OnecBillingStatementBatchDel(ctx context.Context, in *pb.OnecBillingStatementBatchDelReq) (*pb.OnecBillingStatementBatchDelResp, error) {
	l := managerservicelogic.NewOnecBillingStatementBatchDelLogic(ctx, s.svcCtx)
	return l.OnecBillingStatementBatchDel(in)
}

// 立即生成账单
func (s *ManagerServiceServer) OnecBillingStatementGenerate(ctx context.Context, in *pb.OnecBillingStatementGenerateReq) (*pb.OnecBillingStatementGenerateResp, error) {
	l := managerservicelogic.NewOnecBillingStatementGenerateLogic(ctx, s.svcCtx)
	return l.OnecBillingStatementGenerate(in)
}

// 生成所有账单
func (s *ManagerServiceServer) OnecBillingStatementGenerateAll(ctx context.Context, in *pb.OnecBillingStatementGenerateAllReq) (*pb.OnecBillingStatementGenerateAllResp, error) {
	l := managerservicelogic.NewOnecBillingStatementGenerateAllLogic(ctx, s.svcCtx)
	return l.OnecBillingStatementGenerateAll(in)
}

// 获取Alertmanager配置
func (s *ManagerServiceServer) GetAlertmanagerConfig(ctx context.Context, in *pb.GetAlertmanagerConfigReq) (*pb.GetAlertmanagerConfigResp, error) {
	l := managerservicelogic.NewGetAlertmanagerConfigLogic(ctx, s.svcCtx)
	return l.GetAlertmanagerConfig(in)
}

// 获取Prometheus配置
func (s *ManagerServiceServer) GetPrometheusConfig(ctx context.Context, in *pb.GetPrometheusConfigReq) (*pb.GetPrometheusConfigResp, error) {
	l := managerservicelogic.NewGetPrometheusConfigLogic(ctx, s.svcCtx)
	return l.GetPrometheusConfig(in)
}

// 配置Alertmanager
func (s *ManagerServiceServer) SetAlertmanagerConfig(ctx context.Context, in *pb.SetAlertmanagerConfigReq) (*pb.SetAlertmanagerConfigResp, error) {
	l := managerservicelogic.NewSetAlertmanagerConfigLogic(ctx, s.svcCtx)
	return l.SetAlertmanagerConfig(in)
}

// 按集群拉取 onec_cluster_node_energy（已删过滤），供工作负载「能耗感知」软偏好
func (s *ManagerServiceServer) ListOnecClusterNodeEnergy(ctx context.Context, in *pb.ListOnecClusterNodeEnergyReq) (*pb.ListOnecClusterNodeEnergyResp, error) {
	l := managerservicelogic.NewListOnecClusterNodeEnergyLogic(ctx, s.svcCtx)
	return l.ListOnecClusterNodeEnergy(in)
}
