// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	alert "github.com/yanshicheng/kube-nova/application/manager-api/internal/handler/alert"
	alertdashboard "github.com/yanshicheng/kube-nova/application/manager-api/internal/handler/alertdashboard"
	app "github.com/yanshicheng/kube-nova/application/manager-api/internal/handler/app"
	billing "github.com/yanshicheng/kube-nova/application/manager-api/internal/handler/billing"
	cluster "github.com/yanshicheng/kube-nova/application/manager-api/internal/handler/cluster"
	monitoring "github.com/yanshicheng/kube-nova/application/manager-api/internal/handler/monitoring"
	node "github.com/yanshicheng/kube-nova/application/manager-api/internal/handler/node"
	project "github.com/yanshicheng/kube-nova/application/manager-api/internal/handler/project"
	projectauditlog "github.com/yanshicheng/kube-nova/application/manager-api/internal/handler/projectauditlog"
	resourcedashboard "github.com/yanshicheng/kube-nova/application/manager-api/internal/handler/resourcedashboard"
	schedule "github.com/yanshicheng/kube-nova/application/manager-api/internal/handler/schedule"
	sync "github.com/yanshicheng/kube-nova/application/manager-api/internal/handler/sync"
	webhook "github.com/yanshicheng/kube-nova/application/manager-api/internal/handler/webhook"
	"github.com/yanshicheng/kube-nova/application/manager-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWTAuthMiddleware},
			[]rest.Route{
				{
					// 创建新的告警规则文件
					Method:  http.MethodPost,
					Path:    "/file",
					Handler: alert.AddAlertRuleFileHandler(serverCtx),
				},
				{
					// 更新告警规则文件信息
					Method:  http.MethodPut,
					Path:    "/file/:id",
					Handler: alert.UpdateAlertRuleFileHandler(serverCtx),
				},
				{
					// 删除告警规则文件
					Method:  http.MethodDelete,
					Path:    "/file/:id",
					Handler: alert.DeleteAlertRuleFileHandler(serverCtx),
				},
				{
					// 根据ID获取告警规则文件详细信息
					Method:  http.MethodGet,
					Path:    "/file/:id",
					Handler: alert.GetAlertRuleFileHandler(serverCtx),
				},
				{
					// 列表查询告警规则文件(无分页)
					Method:  http.MethodGet,
					Path:    "/file/list",
					Handler: alert.ListAlertRuleFileHandler(serverCtx),
				},
				{
					// 搜索告警规则文件列表
					Method:  http.MethodGet,
					Path:    "/file/search",
					Handler: alert.SearchAlertRuleFileHandler(serverCtx),
				},
				{
					// 创建新的告警规则分组
					Method:  http.MethodPost,
					Path:    "/group",
					Handler: alert.AddAlertRuleGroupHandler(serverCtx),
				},
				{
					// 更新告警规则分组信息
					Method:  http.MethodPut,
					Path:    "/group/:id",
					Handler: alert.UpdateAlertRuleGroupHandler(serverCtx),
				},
				{
					// 删除告警规则分组
					Method:  http.MethodDelete,
					Path:    "/group/:id",
					Handler: alert.DeleteAlertRuleGroupHandler(serverCtx),
				},
				{
					// 根据ID获取告警规则分组详细信息
					Method:  http.MethodGet,
					Path:    "/group/:id",
					Handler: alert.GetAlertRuleGroupHandler(serverCtx),
				},
				{
					// 列表查询告警规则分组(无分页)
					Method:  http.MethodGet,
					Path:    "/group/list",
					Handler: alert.ListAlertRuleGroupHandler(serverCtx),
				},
				{
					// 搜索告警规则分组列表
					Method:  http.MethodGet,
					Path:    "/group/search",
					Handler: alert.SearchAlertRuleGroupHandler(serverCtx),
				},
				{
					// 删除告警实例
					Method:  http.MethodDelete,
					Path:    "/instance/:id",
					Handler: alert.DeleteAlertInstanceHandler(serverCtx),
				},
				{
					// 根据ID获取告警实例详细信息
					Method:  http.MethodGet,
					Path:    "/instance/:id",
					Handler: alert.GetAlertInstanceHandler(serverCtx),
				},
				{
					// 批量删除告警实例
					Method:  http.MethodPost,
					Path:    "/instance/batch/delete",
					Handler: alert.BatchDeleteAlertInstanceHandler(serverCtx),
				},
				{
					// 搜索告警实例列表
					Method:  http.MethodGet,
					Path:    "/instance/search",
					Handler: alert.SearchAlertInstanceHandler(serverCtx),
				},
				{
					// 创建新的告警规则
					Method:  http.MethodPost,
					Path:    "/rule",
					Handler: alert.AddAlertRuleHandler(serverCtx),
				},
				{
					// 更新告警规则信息
					Method:  http.MethodPut,
					Path:    "/rule/:id",
					Handler: alert.UpdateAlertRuleHandler(serverCtx),
				},
				{
					// 删除告警规则
					Method:  http.MethodDelete,
					Path:    "/rule/:id",
					Handler: alert.DeleteAlertRuleHandler(serverCtx),
				},
				{
					// 根据ID获取告警规则详细信息
					Method:  http.MethodGet,
					Path:    "/rule/:id",
					Handler: alert.GetAlertRuleHandler(serverCtx),
				},
				{
					// 批量删除告警规则
					Method:  http.MethodPost,
					Path:    "/rule/batch/delete",
					Handler: alert.BatchDeleteAlertRuleHandler(serverCtx),
				},
				{
					// 导出告警规则为YAML
					Method:  http.MethodGet,
					Path:    "/rule/batch/export",
					Handler: alert.BatchExportAlertRulesHandler(serverCtx),
				},
				{
					// 从YAML批量导入告警规则
					Method:  http.MethodPost,
					Path:    "/rule/batch/import",
					Handler: alert.BatchImportAlertRulesHandler(serverCtx),
				},
				{
					// 将告警规则部署到指定集群
					Method:  http.MethodPost,
					Path:    "/rule/deploy",
					Handler: alert.DeployAlertRulesHandler(serverCtx),
				},
				{
					// 部署全部告警规则到指定集群
					Method:  http.MethodPost,
					Path:    "/rule/deploy/all",
					Handler: alert.DeployAllAlertRulesHandler(serverCtx),
				},
				{
					// 导出全部告警规则为ZIP压缩包
					Method:  http.MethodGet,
					Path:    "/rule/export/all",
					Handler: alert.ExportAllAlertRulesHandler(serverCtx),
				},
				{
					// 预览生成的告警规则YAML
					Method:  http.MethodGet,
					Path:    "/rule/preview",
					Handler: alert.PreviewAlertRulesYamlHandler(serverCtx),
				},
				{
					// 搜索告警规则列表
					Method:  http.MethodGet,
					Path:    "/rule/search",
					Handler: alert.SearchAlertRuleHandler(serverCtx),
				},
				{
					// 获取告警规则树形结构
					Method:  http.MethodGet,
					Path:    "/rule/tree",
					Handler: alert.GetAlertRuleTreeHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/manager/v1/alert"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWTAuthMiddleware},
			[]rest.Route{
				{
					// 获取告警维度统计
					Method:  http.MethodGet,
					Path:    "/dimension",
					Handler: alertdashboard.GetAlertDimensionStatsHandler(serverCtx),
				},
				{
					// 获取告警总览统计
					Method:  http.MethodGet,
					Path:    "/overview",
					Handler: alertdashboard.GetAlertOverviewHandler(serverCtx),
				},
				{
					// 获取告警排行榜
					Method:  http.MethodGet,
					Path:    "/ranking",
					Handler: alertdashboard.GetAlertTopRankingHandler(serverCtx),
				},
				{
					// 获取告警实时状态
					Method:  http.MethodGet,
					Path:    "/realtime",
					Handler: alertdashboard.GetAlertRealtimeStatusHandler(serverCtx),
				},
				{
					// 获取告警汇总报告
					Method:  http.MethodGet,
					Path:    "/report",
					Handler: alertdashboard.GetAlertSummaryReportHandler(serverCtx),
				},
				{
					// 获取告警级别统计
					Method:  http.MethodGet,
					Path:    "/severity",
					Handler: alertdashboard.GetAlertSeverityStatsHandler(serverCtx),
				},
				{
					// 获取告警趋势分析
					Method:  http.MethodGet,
					Path:    "/trend",
					Handler: alertdashboard.GetAlertTrendHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/manager/v1/alert/dashboard"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWTAuthMiddleware},
			[]rest.Route{
				{
					// 添加或更新集群应用配置，如果应用已存在则更新，否则创建新应用
					Method:  http.MethodPost,
					Path:    "/",
					Handler: app.AddClusterAppHandler(serverCtx),
				},
				{
					// 根据应用ID获取应用的详细配置信息
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: app.GetClusterAppDetailHandler(serverCtx),
				},
				{
					// 测试中间件是否正常，验证应用的连通性和认证配置
					Method:  http.MethodPost,
					Path:    "/:id/validate",
					Handler: app.ValidateClusterAppHandler(serverCtx),
				},
				{
					// 获取指定集群下的所有应用配置列表
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: app.GetClusterAppListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/manager/v1/app"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWTAuthMiddleware},
			[]rest.Route{
				{
					// 新增计费配置绑定
					Method:  http.MethodPost,
					Path:    "/config-binding",
					Handler: billing.OnecBillingConfigBindingAddHandler(serverCtx),
				},
				{
					// 更新计费配置绑定
					Method:  http.MethodPut,
					Path:    "/config-binding",
					Handler: billing.OnecBillingConfigBindingUpdateHandler(serverCtx),
				},
				{
					// 获取计费配置绑定
					Method:  http.MethodGet,
					Path:    "/config-binding",
					Handler: billing.OnecBillingConfigBindingGetHandler(serverCtx),
				},
				{
					// 删除计费配置绑定
					Method:  http.MethodDelete,
					Path:    "/config-binding/:id",
					Handler: billing.OnecBillingConfigBindingDelHandler(serverCtx),
				},
				{
					// 获取集群费用排行
					Method:  http.MethodGet,
					Path:    "/dashboard/cluster-top",
					Handler: billing.OnecBillingClusterTopHandler(serverCtx),
				},
				{
					// 获取费用构成
					Method:  http.MethodGet,
					Path:    "/dashboard/composition",
					Handler: billing.OnecBillingCostCompositionHandler(serverCtx),
				},
				{
					// 获取项目费用排行
					Method:  http.MethodGet,
					Path:    "/dashboard/project-top",
					Handler: billing.OnecBillingProjectTopHandler(serverCtx),
				},
				{
					// 获取仪表盘统计数据
					Method:  http.MethodGet,
					Path:    "/dashboard/stats",
					Handler: billing.OnecBillingDashboardStatsHandler(serverCtx),
				},
				{
					// 获取费用趋势
					Method:  http.MethodGet,
					Path:    "/dashboard/trend",
					Handler: billing.OnecBillingCostTrendHandler(serverCtx),
				},
				{
					// 新增收费配置
					Method:  http.MethodPost,
					Path:    "/price-config",
					Handler: billing.OnecBillingPriceConfigAddHandler(serverCtx),
				},
				{
					// 更新收费配置
					Method:  http.MethodPut,
					Path:    "/price-config",
					Handler: billing.OnecBillingPriceConfigUpdateHandler(serverCtx),
				},
				{
					// 搜索收费配置
					Method:  http.MethodGet,
					Path:    "/price-config",
					Handler: billing.OnecBillingPriceConfigSearchHandler(serverCtx),
				},
				{
					// 删除收费配置
					Method:  http.MethodDelete,
					Path:    "/price-config/:id",
					Handler: billing.OnecBillingPriceConfigDelHandler(serverCtx),
				},
				{
					// 根据ID获取收费配置
					Method:  http.MethodGet,
					Path:    "/price-config/:id",
					Handler: billing.OnecBillingPriceConfigGetByIdHandler(serverCtx),
				},
				{
					// 搜索账单
					Method:  http.MethodGet,
					Path:    "/statement",
					Handler: billing.OnecBillingStatementSearchHandler(serverCtx),
				},
				{
					// 删除单条账单
					Method:  http.MethodDelete,
					Path:    "/statement/:id",
					Handler: billing.OnecBillingStatementDelHandler(serverCtx),
				},
				{
					// 批量删除账单
					Method:  http.MethodPost,
					Path:    "/statement/batch-delete",
					Handler: billing.OnecBillingStatementBatchDelHandler(serverCtx),
				},
				{
					// 导出账单Excel
					Method:  http.MethodGet,
					Path:    "/statement/export",
					Handler: billing.OnecBillingStatementExportHandler(serverCtx),
				},
				{
					// 立即生成账单
					Method:  http.MethodPost,
					Path:    "/statement/generate",
					Handler: billing.OnecBillingStatementGenerateHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/manager/v1/billing"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWTAuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: cluster.AddClusterHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: cluster.SearchClusterHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:clusterUuid/ingress",
					Handler: cluster.GetClusterIngressDomainsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:clusterUuid/namespaces",
					Handler: cluster.GetClusterNamespacesHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:clusterUuid/network",
					Handler: cluster.GetClusterNetworkHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:clusterUuid/users",
					Handler: cluster.GetClusterMembersHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/:clusterUuid/users",
					Handler: cluster.SetClusterMembersHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/:id",
					Handler: cluster.UpdateClusterHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: cluster.DeleteClusterHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: cluster.GetClusterDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/:id/auth",
					Handler: cluster.UpdateClusterAuthInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id/auth",
					Handler: cluster.GetClusterAuthInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/:id/avatar",
					Handler: cluster.UpdateClusterAvatarHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id/resource",
					Handler: cluster.GetClusterResourceInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/:resourceId/storage",
					Handler: cluster.UpdateClusterStorageCapacityHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/test",
					Handler: cluster.TestClusterConnectivityHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/manager/v1/cluster"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWTAuthMiddleware},
			[]rest.Route{
				{
					// 获取指定集群的Alertmanager配置
					Method:  http.MethodGet,
					Path:    "/alertmanager/:clusterUuid/config",
					Handler: monitoring.GetAlertmanagerConfigHandler(serverCtx),
				},
				{
					// 配置指定集群的Alertmanager
					Method:  http.MethodPost,
					Path:    "/alertmanager/:clusterUuid/config",
					Handler: monitoring.SetAlertmanagerConfigHandler(serverCtx),
				},
				{
					// 获取指定集群的Prometheus配置
					Method:  http.MethodGet,
					Path:    "/prometheus/:clusterUuid/config",
					Handler: monitoring.GetPrometheusConfigHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/manager/v1/monitoring"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWTAuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: node.GetNodeListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: node.GetNodeDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id/annotations",
					Handler: node.GetNodeAnnotationsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/:id/annotations",
					Handler: node.AddNodeAnnotationHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id/annotations",
					Handler: node.DeleteNodeAnnotationHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/:id/evict",
					Handler: node.EvictNodeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id/labels",
					Handler: node.GetNodeLabelsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/:id/labels",
					Handler: node.AddNodeLabelHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id/labels",
					Handler: node.DeleteNodeLabelHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/:id/schedule",
					Handler: node.UpdateNodeScheduleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id/taints",
					Handler: node.GetNodeTaintsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/:id/taints",
					Handler: node.AddNodeTaintHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id/taints",
					Handler: node.DeleteNodeTaintHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id/yaml",
					Handler: node.GetNodeYamlHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/manager/v1/node"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWTAuthMiddleware},
			[]rest.Route{
				{
					// 创建新项目
					Method:  http.MethodPost,
					Path:    "/",
					Handler: project.AddProjectHandler(serverCtx),
				},
				{
					// 更新项目基本信息
					Method:  http.MethodPut,
					Path:    "/:id",
					Handler: project.UpdateProjectHandler(serverCtx),
				},
				{
					// 软删除项目
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: project.DeleteProjectHandler(serverCtx),
				},
				{
					// 根据ID获取项目详细信息
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: project.GetProjectHandler(serverCtx),
				},
				{
					// 批量添加项目管理员，使用事务先删除所有管理员再批量添加
					Method:  http.MethodPost,
					Path:    "/admin",
					Handler: project.AddProjectAdminHandler(serverCtx),
				},
				{
					// 根据项目ID获取所有管理员列表
					Method:  http.MethodGet,
					Path:    "/admin/list",
					Handler: project.GetProjectAdminsHandler(serverCtx),
				},
				{
					// 为项目分配集群资源配额
					Method:  http.MethodPost,
					Path:    "/cluster",
					Handler: project.AddProjectClusterHandler(serverCtx),
				},
				{
					// 更新项目集群资源配额，不能小于已使用量
					Method:  http.MethodPut,
					Path:    "/cluster/:id",
					Handler: project.UpdateProjectClusterHandler(serverCtx),
				},
				{
					// 软删除项目集群配额，需确保没有工作空间在使用
					Method:  http.MethodDelete,
					Path:    "/cluster/:id",
					Handler: project.DeleteProjectClusterHandler(serverCtx),
				},
				{
					// 根据ID获取项目集群配额详细信息
					Method:  http.MethodGet,
					Path:    "/cluster/:id",
					Handler: project.GetProjectClusterHandler(serverCtx),
				},
				{
					// 搜索项目的集群配额列表，projectId为必传参数
					Method:  http.MethodGet,
					Path:    "/cluster/search",
					Handler: project.SearchProjectClusterHandler(serverCtx),
				},
				{
					// 同集群迁移版本
					Method:  http.MethodPost,
					Path:    "/migrate/version",
					Handler: project.MigrateVersionOnProjectHandler(serverCtx),
				},
				{
					// 同集群迁移工作空间
					Method:  http.MethodPost,
					Path:    "/migrate/workspace",
					Handler: project.MigrateWorkspaceOnProjectHandler(serverCtx),
				},
				{
					// 搜索项目列表，支持分页和条件筛选
					Method:  http.MethodGet,
					Path:    "/search",
					Handler: project.SearchProjectHandler(serverCtx),
				},
				{
					// 根据用户ID查询项目列表
					Method:  http.MethodGet,
					Path:    "/user",
					Handler: project.GetProjectsByUserIdHandler(serverCtx),
				},
				{
					// 创建新的项目工作空间（Kubernetes命名空间）
					Method:  http.MethodPost,
					Path:    "/workspace",
					Handler: project.AddProjectWorkspaceHandler(serverCtx),
				},
				{
					// 更新工作空间配置，资源配额不能超过项目集群限制
					Method:  http.MethodPut,
					Path:    "/workspace/:id",
					Handler: project.UpdateProjectWorkspaceHandler(serverCtx),
				},
				{
					// 软删除工作空间，并同步更新项目集群资源使用量
					Method:  http.MethodDelete,
					Path:    "/workspace/:id",
					Handler: project.DeleteProjectWorkspaceHandler(serverCtx),
				},
				{
					// 根据ID获取工作空间详细信息
					Method:  http.MethodGet,
					Path:    "/workspace/:id",
					Handler: project.GetProjectWorkspaceHandler(serverCtx),
				},
				{
					// 搜索项目的工作空间列表，projectClusterId为必传参数
					Method:  http.MethodGet,
					Path:    "/workspace/search",
					Handler: project.SearchProjectWorkspaceHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/manager/v1/project"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWTAuthMiddleware},
			[]rest.Route{
				{
					// 删除指定的审计日志记录
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: projectauditlog.DeleteProjectAuditLogHandler(serverCtx),
				},
				{
					// 批量删除审计日志记录，最多100条
					Method:  http.MethodPost,
					Path:    "/batch-delete",
					Handler: projectauditlog.BatchDeleteProjectAuditLogHandler(serverCtx),
				},
				{
					// 删除指定天数之前的审计日志数据，用于定期清理历史数据
					Method:  http.MethodPost,
					Path:    "/delete-before-days",
					Handler: projectauditlog.DeleteProjectAuditLogBeforeDaysHandler(serverCtx),
				},
				{
					// 搜索审计日志列表，支持分页和多条件筛选
					Method:  http.MethodGet,
					Path:    "/search",
					Handler: projectauditlog.SearchProjectAuditLogHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/manager/v1/project/audit-log"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWTAuthMiddleware},
			[]rest.Route{
				{
					// 获取集群资源排行
					Method:  http.MethodGet,
					Path:    "/ranking/cluster",
					Handler: resourcedashboard.GetClusterResourceRankingHandler(serverCtx),
				},
				{
					// 获取项目资源排行
					Method:  http.MethodGet,
					Path:    "/ranking/project",
					Handler: resourcedashboard.GetProjectResourceRankingHandler(serverCtx),
				},
				{
					// 获取工作空间资源排行
					Method:  http.MethodGet,
					Path:    "/ranking/workspace",
					Handler: resourcedashboard.GetWorkspaceResourceRankingHandler(serverCtx),
				},
				{
					// 获取资源仪表盘汇总数据
					Method:  http.MethodGet,
					Path:    "/summary",
					Handler: resourcedashboard.GetResourceDashboardSummaryHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/manager/v1/resource/dashboard"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWTAuthMiddleware},
			[]rest.Route{
				{
					// 生成电-储-算感知分层强化学习调度计划
					Method:  http.MethodPost,
					Path:    "/rl-plan",
					Handler: schedule.BuildRlSchedulePlanHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/manager/v1/schedule"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWTAuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/cluster/:id",
					Handler: sync.ClusterOneSyncHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/cluster/:id/resource",
					Handler: sync.ClusterResourceSyncHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/cluster/all",
					Handler: sync.ClusterAllSyncHandler(serverCtx),
				},
				{
					// 同步项目相关数据
					Method:  http.MethodPost,
					Path:    "/project/:id",
					Handler: sync.ProjectOneSyncHandler(serverCtx),
				},
				{
					// 同步计算项目集群的资源使用量，更新到数据库
					Method:  http.MethodPost,
					Path:    "/project/:id/sync",
					Handler: sync.ProjectOneClusterResourceHandler(serverCtx),
				},
				{
					// 同步所有项目集群配额
					Method:  http.MethodPost,
					Path:    "/project/all",
					Handler: sync.ProjectAllClusterResourceHandler(serverCtx),
				},
				{
					// 同步工作空间的实际运行状态和资源使用情况
					Method:  http.MethodPost,
					Path:    "/workspace/:id/sync",
					Handler: sync.ProjectWorkspaceSyncHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/manager/v1/sync"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 接收 Alertmanager 告警
				Method:  http.MethodPost,
				Path:    "/alerts",
				Handler: webhook.ReceiveAlertmanagerWebhookHandler(serverCtx),
			},
		},
		rest.WithPrefix("/manager/v1/webhook"),
	)
}
