apiVersion: v1
kind: Service
metadata:
  name: portal-api
  namespace: cloud-back
spec:
  selector:
    app: portal-api
  ports:
    - name: http
      port: 8810
      targetPort: 8810
      nodePort: 30810
  type: NodePort
