// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: manager.proto

package managerservice

import (
	"context"

	"github.com/yanshicheng/kube-nova/application/manager-rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddAlertRuleFileReq                  = pb.AddAlertRuleFileReq
	AddAlertRuleFileResp                 = pb.AddAlertRuleFileResp
	AddAlertRuleGroupReq                 = pb.AddAlertRuleGroupReq
	AddAlertRuleGroupResp                = pb.AddAlertRuleGroupResp
	AddAlertRuleReq                      = pb.AddAlertRuleReq
	AddAlertRuleResp                     = pb.AddAlertRuleResp
	AddClusterAppReq                     = pb.AddClusterAppReq
	AddClusterAppResp                    = pb.AddClusterAppResp
	AddClusterRequest                    = pb.AddClusterRequest
	AddClusterResponse                   = pb.AddClusterResponse
	AddOnecProjectAdminReq               = pb.AddOnecProjectAdminReq
	AddOnecProjectAdminResp              = pb.AddOnecProjectAdminResp
	AddOnecProjectApplicationReq         = pb.AddOnecProjectApplicationReq
	AddOnecProjectApplicationResp        = pb.AddOnecProjectApplicationResp
	AddOnecProjectAuditLogReq            = pb.AddOnecProjectAuditLogReq
	AddOnecProjectAuditLogResp           = pb.AddOnecProjectAuditLogResp
	AddOnecProjectClusterReq             = pb.AddOnecProjectClusterReq
	AddOnecProjectClusterResp            = pb.AddOnecProjectClusterResp
	AddOnecProjectReq                    = pb.AddOnecProjectReq
	AddOnecProjectResp                   = pb.AddOnecProjectResp
	AddOnecProjectVersionReq             = pb.AddOnecProjectVersionReq
	AddOnecProjectVersionResp            = pb.AddOnecProjectVersionResp
	AddOnecProjectWorkspaceReq           = pb.AddOnecProjectWorkspaceReq
	AddOnecProjectWorkspaceResp          = pb.AddOnecProjectWorkspaceResp
	AppDefaultConfigReq                  = pb.AppDefaultConfigReq
	AppDefaultConfigResp                 = pb.AppDefaultConfigResp
	BatchDelAlertInstancesReq            = pb.BatchDelAlertInstancesReq
	BatchDelAlertInstancesResp           = pb.BatchDelAlertInstancesResp
	BatchDelAlertRuleReq                 = pb.BatchDelAlertRuleReq
	BatchDelAlertRuleResp                = pb.BatchDelAlertRuleResp
	BatchDelOnecProjectAuditLogReq       = pb.BatchDelOnecProjectAuditLogReq
	BatchDelOnecProjectAuditLogResp      = pb.BatchDelOnecProjectAuditLogResp
	BatchExportAlertRulesReq             = pb.BatchExportAlertRulesReq
	BatchExportAlertRulesResp            = pb.BatchExportAlertRulesResp
	BatchImportAlertRulesReq             = pb.BatchImportAlertRulesReq
	BatchImportAlertRulesResp            = pb.BatchImportAlertRulesResp
	ClusterAppDetailReq                  = pb.ClusterAppDetailReq
	ClusterAppDetailResp                 = pb.ClusterAppDetailResp
	ClusterAppListReq                    = pb.ClusterAppListReq
	ClusterAppListResp                   = pb.ClusterAppListResp
	ClusterAppValidateReq                = pb.ClusterAppValidateReq
	ClusterAppValidateResp               = pb.ClusterAppValidateResp
	ClusterAuthInfoReq                   = pb.ClusterAuthInfoReq
	ClusterAuthInfoResp                  = pb.ClusterAuthInfoResp
	Cluster                              = pb.Cluster
	ClusterDetailReq                     = pb.ClusterDetailReq
	ClusterDetailResp                    = pb.ClusterDetailResp
	ClusterEvictReq                      = pb.ClusterEvictReq
	ClusterEvictResp                     = pb.ClusterEvictResp
	ClusterNodeAddAnnotationsReq         = pb.ClusterNodeAddAnnotationsReq
	ClusterNodeAddAnnotationsResp        = pb.ClusterNodeAddAnnotationsResp
	ClusterNodeAddLabelsReq              = pb.ClusterNodeAddLabelsReq
	ClusterNodeAddTaintReq               = pb.ClusterNodeAddTaintReq
	ClusterNodeAddTaintResp              = pb.ClusterNodeAddTaintResp
	ClusterNodeAnnotationsListReq        = pb.ClusterNodeAnnotationsListReq
	ClusterNodeAnnotationsListResp       = pb.ClusterNodeAnnotationsListResp
	ClusterNodeDeleteAnnotationsReq      = pb.ClusterNodeDeleteAnnotationsReq
	ClusterNodeDeleteAnnotationsResp     = pb.ClusterNodeDeleteAnnotationsResp
	ClusterNodeDeleteLabelsReq           = pb.ClusterNodeDeleteLabelsReq
	ClusterNodeDeleteTaintReq            = pb.ClusterNodeDeleteTaintReq
	ClusterNodeDetailReq                 = pb.ClusterNodeDetailReq
	ClusterNodeDisableReq                = pb.ClusterNodeDisableReq
	ClusterNodeDisableResp               = pb.ClusterNodeDisableResp
	ClusterNodeInfoReq                   = pb.ClusterNodeInfoReq
	ClusterNodeInfoResp                  = pb.ClusterNodeInfoResp
	ClusterNodeLabelsListReq             = pb.ClusterNodeLabelsListReq
	ClusterNodeLabelsListResp            = pb.ClusterNodeLabelsListResp
	ClusterNodeTaintsListReq             = pb.ClusterNodeTaintsListReq
	ClusterNodeTaintsListResp            = pb.ClusterNodeTaintsListResp
	ClusterNodeYamlDescribeReq           = pb.ClusterNodeYamlDescribeReq
	ClusterNodeYamlDescribeResp          = pb.ClusterNodeYamlDescribeResp
	ClusterResourceInfoReq               = pb.ClusterResourceInfoReq
	ClusterResourceInfoResp              = pb.ClusterResourceInfoResp
	ClusterResourceRankingReq            = pb.ClusterResourceRankingReq
	ClusterResourceRankingResp           = pb.ClusterResourceRankingResp
	ClusterResourceSyncReq               = pb.ClusterResourceSyncReq
	ClusterResourceSyncResp              = pb.ClusterResourceSyncResp
	ClusterSyncAllReq                    = pb.ClusterSyncAllReq
	ClusterSyncAllResp                   = pb.ClusterSyncAllResp
	ClusterTestConnectReq                = pb.ClusterTestConnectReq
	ClusterTestConnectResp               = pb.ClusterTestConnectResp
	ClusterUpdateAuthInfoReq             = pb.ClusterUpdateAuthInfoReq
	ClusterUpdateAuthInfoResp            = pb.ClusterUpdateAuthInfoResp
	ClusterUpdateAvatarReq               = pb.ClusterUpdateAvatarReq
	ClusterUpdateAvatarResp              = pb.ClusterUpdateAvatarResp
	DelAlertInstancesReq                 = pb.DelAlertInstancesReq
	DelAlertInstancesResp                = pb.DelAlertInstancesResp
	DelAlertRuleFileReq                  = pb.DelAlertRuleFileReq
	DelAlertRuleFileResp                 = pb.DelAlertRuleFileResp
	DelAlertRuleGroupReq                 = pb.DelAlertRuleGroupReq
	DelAlertRuleGroupResp                = pb.DelAlertRuleGroupResp
	DelAlertRuleReq                      = pb.DelAlertRuleReq
	DelAlertRuleResp                     = pb.DelAlertRuleResp
	DelOnecProjectApplicationReq         = pb.DelOnecProjectApplicationReq
	DelOnecProjectApplicationResp        = pb.DelOnecProjectApplicationResp
	DelOnecProjectAuditLogBeforeDaysReq  = pb.DelOnecProjectAuditLogBeforeDaysReq
	DelOnecProjectAuditLogBeforeDaysResp = pb.DelOnecProjectAuditLogBeforeDaysResp
	DelOnecProjectAuditLogReq            = pb.DelOnecProjectAuditLogReq
	DelOnecProjectAuditLogResp           = pb.DelOnecProjectAuditLogResp
	DelOnecProjectClusterReq             = pb.DelOnecProjectClusterReq
	DelOnecProjectClusterResp            = pb.DelOnecProjectClusterResp
	DelOnecProjectReq                    = pb.DelOnecProjectReq
	DelOnecProjectResp                   = pb.DelOnecProjectResp
	DelOnecProjectVersionReq             = pb.DelOnecProjectVersionReq
	DelOnecProjectVersionResp            = pb.DelOnecProjectVersionResp
	DelOnecProjectWorkspaceReq           = pb.DelOnecProjectWorkspaceReq
	DelOnecProjectWorkspaceResp          = pb.DelOnecProjectWorkspaceResp
	DeleteClusterReq                     = pb.DeleteClusterReq
	DeleteClusterResp                    = pb.DeleteClusterResp
	DeployAlertRulesReq                  = pb.DeployAlertRulesReq
	DeployAlertRulesResp                 = pb.DeployAlertRulesResp
	DeployAllAlertRulesReq               = pb.DeployAllAlertRulesReq
	DeployAllAlertRulesResp              = pb.DeployAllAlertRulesResp
	ExportAllAlertRulesReq               = pb.ExportAllAlertRulesReq
	ExportAllAlertRulesResp              = pb.ExportAllAlertRulesResp
	GetAlertDimensionStatsReq            = pb.GetAlertDimensionStatsReq
	GetAlertDimensionStatsResp           = pb.GetAlertDimensionStatsResp
	GetAlertInstancesByIdReq             = pb.GetAlertInstancesByIdReq
	GetAlertInstancesByIdResp            = pb.GetAlertInstancesByIdResp
	GetAlertOverviewReq                  = pb.GetAlertOverviewReq
	GetAlertOverviewResp                 = pb.GetAlertOverviewResp
	GetAlertRealtimeStatusReq            = pb.GetAlertRealtimeStatusReq
	GetAlertRealtimeStatusResp           = pb.GetAlertRealtimeStatusResp
	GetAlertRuleByIdReq                  = pb.GetAlertRuleByIdReq
	GetAlertRuleByIdResp                 = pb.GetAlertRuleByIdResp
	GetAlertRuleFileByIdReq              = pb.GetAlertRuleFileByIdReq
	GetAlertRuleFileByIdResp             = pb.GetAlertRuleFileByIdResp
	GetAlertRuleGroupByIdReq             = pb.GetAlertRuleGroupByIdReq
	GetAlertRuleGroupByIdResp            = pb.GetAlertRuleGroupByIdResp
	GetAlertRuleTreeReq                  = pb.GetAlertRuleTreeReq
	GetAlertRuleTreeResp                 = pb.GetAlertRuleTreeResp
	GetAlertSeverityStatsReq             = pb.GetAlertSeverityStatsReq
	GetAlertSeverityStatsResp            = pb.GetAlertSeverityStatsResp
	GetAlertSummaryReportReq             = pb.GetAlertSummaryReportReq
	GetAlertSummaryReportResp            = pb.GetAlertSummaryReportResp
	GetAlertTopRankingReq                = pb.GetAlertTopRankingReq
	GetAlertTopRankingResp               = pb.GetAlertTopRankingResp
	GetAlertTrendReq                     = pb.GetAlertTrendReq
	GetAlertTrendResp                    = pb.GetAlertTrendResp
	GetAlertmanagerConfigReq             = pb.GetAlertmanagerConfigReq
	GetAlertmanagerConfigResp            = pb.GetAlertmanagerConfigResp
	GetClusterAuthInfoReq                = pb.GetClusterAuthInfoReq
	GetClusterAuthInfoResp               = pb.GetClusterAuthInfoResp
	GetClusterDefaultDomainSuffixReq     = pb.GetClusterDefaultDomainSuffixReq
	GetClusterDefaultDomainSuffixResp    = pb.GetClusterDefaultDomainSuffixResp
	GetClusterDomainListReq              = pb.GetClusterDomainListReq
	GetClusterDomainListResp             = pb.GetClusterDomainListResp
	GetClusterLbListReq                  = pb.GetClusterLbListReq
	GetClusterLbListResp                 = pb.GetClusterLbListResp
	GetClusterNetworkReq                 = pb.GetClusterNetworkReq
	GetClusterNetworkResp                = pb.GetClusterNetworkResp
	GetClusterNsDetailReq                = pb.GetClusterNsDetailReq
	GetClusterNsDetailResp               = pb.GetClusterNsDetailResp
	GetClusterNsReq                      = pb.GetClusterNsReq
	GetClusterNsResp                     = pb.GetClusterNsResp
	GetOnecProjectAdminsByProjectIdReq   = pb.GetOnecProjectAdminsByProjectIdReq
	GetOnecProjectAdminsByProjectIdResp  = pb.GetOnecProjectAdminsByProjectIdResp
	GetOnecProjectApplicationByIdReq     = pb.GetOnecProjectApplicationByIdReq
	GetOnecProjectApplicationByIdResp    = pb.GetOnecProjectApplicationByIdResp
	GetOnecProjectByIdReq                = pb.GetOnecProjectByIdReq
	GetOnecProjectByIdResp               = pb.GetOnecProjectByIdResp
	GetOnecProjectClusterByIdReq         = pb.GetOnecProjectClusterByIdReq
	GetOnecProjectClusterByIdResp        = pb.GetOnecProjectClusterByIdResp
	GetOnecProjectVersionDetailReq       = pb.GetOnecProjectVersionDetailReq
	GetOnecProjectVersionDetailResp      = pb.GetOnecProjectVersionDetailResp
	GetOnecProjectWorkspaceByIdReq       = pb.GetOnecProjectWorkspaceByIdReq
	GetOnecProjectWorkspaceByIdResp      = pb.GetOnecProjectWorkspaceByIdResp
	GetOnecProjectsByUserIdReq           = pb.GetOnecProjectsByUserIdReq
	GetOnecProjectsByUserIdResp          = pb.GetOnecProjectsByUserIdResp
	GetPrometheusConfigReq               = pb.GetPrometheusConfigReq
	GetPrometheusConfigResp              = pb.GetPrometheusConfigResp
	ListAlertRuleFileReq                 = pb.ListAlertRuleFileReq
	ListAlertRuleFileResp                = pb.ListAlertRuleFileResp
	ListAlertRuleGroupReq                = pb.ListAlertRuleGroupReq
	ListAlertRuleGroupResp               = pb.ListAlertRuleGroupResp
	ListOnecClusterNodeEnergyReq         = pb.ListOnecClusterNodeEnergyReq
	ListOnecClusterNodeEnergyResp        = pb.ListOnecClusterNodeEnergyResp
	MigrateWorkspaceReq                  = pb.MigrateWorkspaceReq
	MigrateWorkspaceResp                 = pb.MigrateWorkspaceResp
	OnecBillingClusterTopReq             = pb.OnecBillingClusterTopReq
	OnecBillingClusterTopResp            = pb.OnecBillingClusterTopResp
	OnecBillingConfigBindingAddReq       = pb.OnecBillingConfigBindingAddReq
	OnecBillingConfigBindingAddResp      = pb.OnecBillingConfigBindingAddResp
	OnecBillingConfigBindingDelReq       = pb.OnecBillingConfigBindingDelReq
	OnecBillingConfigBindingDelResp      = pb.OnecBillingConfigBindingDelResp
	OnecBillingConfigBindingGetReq       = pb.OnecBillingConfigBindingGetReq
	OnecBillingConfigBindingGetResp      = pb.OnecBillingConfigBindingGetResp
	OnecBillingConfigBindingUpdateReq    = pb.OnecBillingConfigBindingUpdateReq
	OnecBillingConfigBindingUpdateResp   = pb.OnecBillingConfigBindingUpdateResp
	OnecBillingCostCompositionReq        = pb.OnecBillingCostCompositionReq
	OnecBillingCostCompositionResp       = pb.OnecBillingCostCompositionResp
	OnecBillingCostTrendReq              = pb.OnecBillingCostTrendReq
	OnecBillingCostTrendResp             = pb.OnecBillingCostTrendResp
	OnecBillingDashboardStatsReq         = pb.OnecBillingDashboardStatsReq
	OnecBillingDashboardStatsResp        = pb.OnecBillingDashboardStatsResp
	OnecBillingPriceConfigAddReq         = pb.OnecBillingPriceConfigAddReq
	OnecBillingPriceConfigAddResp        = pb.OnecBillingPriceConfigAddResp
	OnecBillingPriceConfigDelReq         = pb.OnecBillingPriceConfigDelReq
	OnecBillingPriceConfigDelResp        = pb.OnecBillingPriceConfigDelResp
	OnecBillingPriceConfigGetByIdReq     = pb.OnecBillingPriceConfigGetByIdReq
	OnecBillingPriceConfigGetByIdResp    = pb.OnecBillingPriceConfigGetByIdResp
	OnecBillingPriceConfigSearchReq      = pb.OnecBillingPriceConfigSearchReq
	OnecBillingPriceConfigSearchResp     = pb.OnecBillingPriceConfigSearchResp
	OnecBillingPriceConfigUpdateReq      = pb.OnecBillingPriceConfigUpdateReq
	OnecBillingPriceConfigUpdateResp     = pb.OnecBillingPriceConfigUpdateResp
	OnecBillingProjectTopReq             = pb.OnecBillingProjectTopReq
	OnecBillingProjectTopResp            = pb.OnecBillingProjectTopResp
	OnecBillingStatementBatchDelReq      = pb.OnecBillingStatementBatchDelReq
	OnecBillingStatementBatchDelResp     = pb.OnecBillingStatementBatchDelResp
	OnecBillingStatementDelReq           = pb.OnecBillingStatementDelReq
	OnecBillingStatementDelResp          = pb.OnecBillingStatementDelResp
	OnecBillingStatementGenerateAllReq   = pb.OnecBillingStatementGenerateAllReq
	OnecBillingStatementGenerateAllResp  = pb.OnecBillingStatementGenerateAllResp
	OnecBillingStatementGenerateReq      = pb.OnecBillingStatementGenerateReq
	OnecBillingStatementGenerateResp     = pb.OnecBillingStatementGenerateResp
	OnecBillingStatementSearchReq        = pb.OnecBillingStatementSearchReq
	OnecBillingStatementSearchResp       = pb.OnecBillingStatementSearchResp
	OnecClusterNodeResp                  = pb.OnecClusterNodeResp
	PreviewAlertRulesYamlReq             = pb.PreviewAlertRulesYamlReq
	PreviewAlertRulesYamlResp            = pb.PreviewAlertRulesYamlResp
	ProjectClusterSyncReq                = pb.ProjectClusterSyncReq
	ProjectClusterSyncResp               = pb.ProjectClusterSyncResp
	ProjectQuotaSyncReq                  = pb.ProjectQuotaSyncReq
	ProjectQuotaSyncResp                 = pb.ProjectQuotaSyncResp
	ProjectResourceRankingReq            = pb.ProjectResourceRankingReq
	ProjectResourceRankingResp           = pb.ProjectResourceRankingResp
	ProjectSyncReq                       = pb.ProjectSyncReq
	ProjectSyncResp                      = pb.ProjectSyncResp
	ProjectWorkspaceSyncReq              = pb.ProjectWorkspaceSyncReq
	ProjectWorkspaceSyncResp             = pb.ProjectWorkspaceSyncResp
	ReceiveAlertmanagerWebhookReq        = pb.ReceiveAlertmanagerWebhookReq
	ReceiveAlertmanagerWebhookResp       = pb.ReceiveAlertmanagerWebhookResp
	ResourceDashboardSummaryReq          = pb.ResourceDashboardSummaryReq
	ResourceDashboardSummaryResp         = pb.ResourceDashboardSummaryResp
	SearchAlertInstancesReq              = pb.SearchAlertInstancesReq
	SearchAlertInstancesResp             = pb.SearchAlertInstancesResp
	SearchAlertRuleFileReq               = pb.SearchAlertRuleFileReq
	SearchAlertRuleFileResp              = pb.SearchAlertRuleFileResp
	SearchAlertRuleGroupReq              = pb.SearchAlertRuleGroupReq
	SearchAlertRuleGroupResp             = pb.SearchAlertRuleGroupResp
	SearchAlertRuleReq                   = pb.SearchAlertRuleReq
	SearchAlertRuleResp                  = pb.SearchAlertRuleResp
	SearchClusterReq                     = pb.SearchClusterReq
	SearchClusterResp                    = pb.SearchClusterResp
	SearchOnecProjectApplicationReq      = pb.SearchOnecProjectApplicationReq
	SearchOnecProjectApplicationResp     = pb.SearchOnecProjectApplicationResp
	SearchOnecProjectAuditLogReq         = pb.SearchOnecProjectAuditLogReq
	SearchOnecProjectAuditLogResp        = pb.SearchOnecProjectAuditLogResp
	SearchOnecProjectClusterReq          = pb.SearchOnecProjectClusterReq
	SearchOnecProjectClusterResp         = pb.SearchOnecProjectClusterResp
	SearchOnecProjectReq                 = pb.SearchOnecProjectReq
	SearchOnecProjectResp                = pb.SearchOnecProjectResp
	SearchOnecProjectVersionReq          = pb.SearchOnecProjectVersionReq
	SearchOnecProjectVersionResp         = pb.SearchOnecProjectVersionResp
	SearchOnecProjectWorkspaceReq        = pb.SearchOnecProjectWorkspaceReq
	SearchOnecProjectWorkspaceResp       = pb.SearchOnecProjectWorkspaceResp
	SaveSchedulePlanReq                  = pb.SaveSchedulePlanReq
	SaveSchedulePlanResp                 = pb.SaveSchedulePlanResp
	SetAlertmanagerConfigReq             = pb.SetAlertmanagerConfigReq
	SetAlertmanagerConfigResp            = pb.SetAlertmanagerConfigResp
	SyncClusterReq                       = pb.SyncClusterReq
	SyncClusterResp                      = pb.SyncClusterResp
	UpdateAlertRuleFileReq               = pb.UpdateAlertRuleFileReq
	UpdateAlertRuleFileResp              = pb.UpdateAlertRuleFileResp
	UpdateAlertRuleGroupReq              = pb.UpdateAlertRuleGroupReq
	UpdateAlertRuleGroupResp             = pb.UpdateAlertRuleGroupResp
	UpdateAlertRuleReq                   = pb.UpdateAlertRuleReq
	UpdateAlertRuleResp                  = pb.UpdateAlertRuleResp
	UpdateClusterReq                     = pb.UpdateClusterReq
	UpdateClusterResp                    = pb.UpdateClusterResp
	UpdateClusterStorageCapacityReq      = pb.UpdateClusterStorageCapacityReq
	UpdateClusterStorageCapacityResp     = pb.UpdateClusterStorageCapacityResp
	UpdateOnecProjectApplicationReq      = pb.UpdateOnecProjectApplicationReq
	UpdateOnecProjectApplicationResp     = pb.UpdateOnecProjectApplicationResp
	UpdateOnecProjectClusterReq          = pb.UpdateOnecProjectClusterReq
	UpdateOnecProjectClusterResp         = pb.UpdateOnecProjectClusterResp
	UpdateOnecProjectReq                 = pb.UpdateOnecProjectReq
	UpdateOnecProjectResp                = pb.UpdateOnecProjectResp
	UpdateOnecProjectWorkspaceReq        = pb.UpdateOnecProjectWorkspaceReq
	UpdateOnecProjectWorkspaceResp       = pb.UpdateOnecProjectWorkspaceResp
	UpdateSchedulePlanStatusReq          = pb.UpdateSchedulePlanStatusReq
	UpdateSchedulePlanStatusResp         = pb.UpdateSchedulePlanStatusResp
	WorkspaceResourceRankingReq          = pb.WorkspaceResourceRankingReq
	WorkspaceResourceRankingResp         = pb.WorkspaceResourceRankingResp

	ManagerService interface {
		// //通过 clusterUuid 和 namespace 获取 详情信息
		GetClusterNsDetail(ctx context.Context, in *GetClusterNsDetailReq, opts ...grpc.CallOption) (*GetClusterNsDetailResp, error)
		// 获取某一个集群的所有ns
		GetClusterNs(ctx context.Context, in *GetClusterNsReq, opts ...grpc.CallOption) (*GetClusterNsResp, error)
		// -----------------------告警实例表-----------------------
		AlertInstancesDel(ctx context.Context, in *DelAlertInstancesReq, opts ...grpc.CallOption) (*DelAlertInstancesResp, error)
		AlertInstancesByIdGet(ctx context.Context, in *GetAlertInstancesByIdReq, opts ...grpc.CallOption) (*GetAlertInstancesByIdResp, error)
		AlertInstancesSearch(ctx context.Context, in *SearchAlertInstancesReq, opts ...grpc.CallOption) (*SearchAlertInstancesResp, error)
		AlertInstancesBatchDel(ctx context.Context, in *BatchDelAlertInstancesReq, opts ...grpc.CallOption) (*BatchDelAlertInstancesResp, error)
		// -----------------------告警规则表-----------------------
		AlertRuleFileAdd(ctx context.Context, in *AddAlertRuleFileReq, opts ...grpc.CallOption) (*AddAlertRuleFileResp, error)
		AlertRuleFileUpdate(ctx context.Context, in *UpdateAlertRuleFileReq, opts ...grpc.CallOption) (*UpdateAlertRuleFileResp, error)
		AlertRuleFileDel(ctx context.Context, in *DelAlertRuleFileReq, opts ...grpc.CallOption) (*DelAlertRuleFileResp, error)
		AlertRuleFileGetById(ctx context.Context, in *GetAlertRuleFileByIdReq, opts ...grpc.CallOption) (*GetAlertRuleFileByIdResp, error)
		AlertRuleFileSearch(ctx context.Context, in *SearchAlertRuleFileReq, opts ...grpc.CallOption) (*SearchAlertRuleFileResp, error)
		AlertRuleFileList(ctx context.Context, in *ListAlertRuleFileReq, opts ...grpc.CallOption) (*ListAlertRuleFileResp, error)
		// ===================== 告警规则分组表 =====================
		AlertRuleGroupAdd(ctx context.Context, in *AddAlertRuleGroupReq, opts ...grpc.CallOption) (*AddAlertRuleGroupResp, error)
		AlertRuleGroupUpdate(ctx context.Context, in *UpdateAlertRuleGroupReq, opts ...grpc.CallOption) (*UpdateAlertRuleGroupResp, error)
		AlertRuleGroupDel(ctx context.Context, in *DelAlertRuleGroupReq, opts ...grpc.CallOption) (*DelAlertRuleGroupResp, error)
		AlertRuleGroupGetById(ctx context.Context, in *GetAlertRuleGroupByIdReq, opts ...grpc.CallOption) (*GetAlertRuleGroupByIdResp, error)
		AlertRuleGroupSearch(ctx context.Context, in *SearchAlertRuleGroupReq, opts ...grpc.CallOption) (*SearchAlertRuleGroupResp, error)
		AlertRuleGroupList(ctx context.Context, in *ListAlertRuleGroupReq, opts ...grpc.CallOption) (*ListAlertRuleGroupResp, error)
		// ===================== 告警规则表 =====================
		AlertRuleAdd(ctx context.Context, in *AddAlertRuleReq, opts ...grpc.CallOption) (*AddAlertRuleResp, error)
		AlertRuleUpdate(ctx context.Context, in *UpdateAlertRuleReq, opts ...grpc.CallOption) (*UpdateAlertRuleResp, error)
		AlertRuleDel(ctx context.Context, in *DelAlertRuleReq, opts ...grpc.CallOption) (*DelAlertRuleResp, error)
		AlertRuleGetById(ctx context.Context, in *GetAlertRuleByIdReq, opts ...grpc.CallOption) (*GetAlertRuleByIdResp, error)
		AlertRuleSearch(ctx context.Context, in *SearchAlertRuleReq, opts ...grpc.CallOption) (*SearchAlertRuleResp, error)
		AlertRuleBatchDel(ctx context.Context, in *BatchDelAlertRuleReq, opts ...grpc.CallOption) (*BatchDelAlertRuleResp, error)
		// ===================== 导入/导出/部署 =====================
		AlertRulesBatchImport(ctx context.Context, in *BatchImportAlertRulesReq, opts ...grpc.CallOption) (*BatchImportAlertRulesResp, error)
		AlertRulesBatchExport(ctx context.Context, in *BatchExportAlertRulesReq, opts ...grpc.CallOption) (*BatchExportAlertRulesResp, error)
		AlertRulesDeploy(ctx context.Context, in *DeployAlertRulesReq, opts ...grpc.CallOption) (*DeployAlertRulesResp, error)
		AlertRulesPreviewYaml(ctx context.Context, in *PreviewAlertRulesYamlReq, opts ...grpc.CallOption) (*PreviewAlertRulesYamlResp, error)
		AlertRulesExportAll(ctx context.Context, in *ExportAllAlertRulesReq, opts ...grpc.CallOption) (*ExportAllAlertRulesResp, error)
		AlertRulesDeployAll(ctx context.Context, in *DeployAllAlertRulesReq, opts ...grpc.CallOption) (*DeployAllAlertRulesResp, error)
		// ===================== 树形结构 =====================
		AlertRuleTreeGet(ctx context.Context, in *GetAlertRuleTreeReq, opts ...grpc.CallOption) (*GetAlertRuleTreeResp, error)
		// ===================== Alertmanager Webhook =====================
		ReceiveAlertmanagerWebhook(ctx context.Context, in *ReceiveAlertmanagerWebhookReq, opts ...grpc.CallOption) (*ReceiveAlertmanagerWebhookResp, error)
		// 获取集群默认域名后缀
		GetClusterDefaultDomainSuffix(ctx context.Context, in *GetClusterDefaultDomainSuffixReq, opts ...grpc.CallOption) (*GetClusterDefaultDomainSuffixResp, error)
		// 获取集群 node or master lb 列表
		GetClusterLbList(ctx context.Context, in *GetClusterLbListReq, opts ...grpc.CallOption) (*GetClusterLbListResp, error)
		// 通过集群uuid获取集群认证信息
		GetClusterAuthInfo(ctx context.Context, in *GetClusterAuthInfoReq, opts ...grpc.CallOption) (*GetClusterAuthInfoResp, error)
		// 修改集群认证信息
		ClusterUpdateAuthInfo(ctx context.Context, in *ClusterUpdateAuthInfoReq, opts ...grpc.CallOption) (*ClusterUpdateAuthInfoResp, error)
		// 修改集群图标
		ClusterUpdateIcon(ctx context.Context, in *ClusterUpdateAvatarReq, opts ...grpc.CallOption) (*ClusterUpdateAvatarResp, error)
		// 测试集群连通性
		ClusterTestConnect(ctx context.Context, in *ClusterTestConnectReq, opts ...grpc.CallOption) (*ClusterTestConnectResp, error)
		// 删除集群
		ClusterDelete(ctx context.Context, in *DeleteClusterReq, opts ...grpc.CallOption) (*DeleteClusterResp, error)
		// 修改集群
		ClusterUpdate(ctx context.Context, in *UpdateClusterReq, opts ...grpc.CallOption) (*UpdateClusterResp, error)
		ClusterSearch(ctx context.Context, in *SearchClusterReq, opts ...grpc.CallOption) (*SearchClusterResp, error)
		ClusterAdd(ctx context.Context, in *AddClusterRequest, opts ...grpc.CallOption) (*AddClusterResponse, error)
		// 获取 某一个集群 ingressDomain 列表
		GetClusterIngressDomainList(ctx context.Context, in *GetClusterDomainListReq, opts ...grpc.CallOption) (*GetClusterDomainListResp, error)
		GetClusterNetwork(ctx context.Context, in *GetClusterNetworkReq, opts ...grpc.CallOption) (*GetClusterNetworkResp, error)
		UpdateClusterStorageCapacity(ctx context.Context, in *UpdateClusterStorageCapacityReq, opts ...grpc.CallOption) (*UpdateClusterStorageCapacityResp, error)
		// 获取集群详情
		ClusterDetail(ctx context.Context, in *ClusterDetailReq, opts ...grpc.CallOption) (*ClusterDetailResp, error)
		ClusterSync(ctx context.Context, in *SyncClusterReq, opts ...grpc.CallOption) (*SyncClusterResp, error)
		ClusterAuthInfo(ctx context.Context, in *ClusterAuthInfoReq, opts ...grpc.CallOption) (*ClusterAuthInfoResp, error)
		// 集群资源
		ClusterResourceInfo(ctx context.Context, in *ClusterResourceInfoReq, opts ...grpc.CallOption) (*ClusterResourceInfoResp, error)
		// 同步某一个集群资源
		ClusterResourceSync(ctx context.Context, in *ClusterResourceSyncReq, opts ...grpc.CallOption) (*ClusterResourceSyncResp, error)
		ClusterSyncAll(ctx context.Context, in *ClusterSyncAllReq, opts ...grpc.CallOption) (*ClusterSyncAllResp, error)
		// node 相关
		NodeInfo(ctx context.Context, in *ClusterNodeInfoReq, opts ...grpc.CallOption) (*ClusterNodeInfoResp, error)
		NodeDetail(ctx context.Context, in *ClusterNodeDetailReq, opts ...grpc.CallOption) (*OnecClusterNodeResp, error)
		// 获取 node  yaml describe
		NodeYamlDescribe(ctx context.Context, in *ClusterNodeYamlDescribeReq, opts ...grpc.CallOption) (*ClusterNodeYamlDescribeResp, error)
		// labels 相关
		NodeLabelsList(ctx context.Context, in *ClusterNodeLabelsListReq, opts ...grpc.CallOption) (*ClusterNodeLabelsListResp, error)
		// 添加 labels
		NodeAddLabels(ctx context.Context, in *ClusterNodeAddLabelsReq, opts ...grpc.CallOption) (*ClusterNodeDisableResp, error)
		// 删除 labels
		NodeDeleteLabels(ctx context.Context, in *ClusterNodeDeleteLabelsReq, opts ...grpc.CallOption) (*ClusterNodeDisableResp, error)
		// 注解相关
		NodeAddAnnotations(ctx context.Context, in *ClusterNodeAddAnnotationsReq, opts ...grpc.CallOption) (*ClusterNodeAddAnnotationsResp, error)
		// 删除注解
		NodeDeleteAnnotations(ctx context.Context, in *ClusterNodeDeleteAnnotationsReq, opts ...grpc.CallOption) (*ClusterNodeDeleteAnnotationsResp, error)
		// 获取注解列表
		NodeAnnotationsList(ctx context.Context, in *ClusterNodeAnnotationsListReq, opts ...grpc.CallOption) (*ClusterNodeAnnotationsListResp, error)
		// 污点相关
		NodeDisable(ctx context.Context, in *ClusterNodeDisableReq, opts ...grpc.CallOption) (*ClusterNodeDisableResp, error)
		// 添加污点
		NodeAddTaint(ctx context.Context, in *ClusterNodeAddTaintReq, opts ...grpc.CallOption) (*ClusterNodeAddTaintResp, error)
		// 删除污点
		NodeDeleteTaint(ctx context.Context, in *ClusterNodeDeleteTaintReq, opts ...grpc.CallOption) (*ClusterNodeDisableResp, error)
		// 获取污点列表
		NodeTaintList(ctx context.Context, in *ClusterNodeTaintsListReq, opts ...grpc.CallOption) (*ClusterNodeTaintsListResp, error)
		// 驱逐
		NodeEvict(ctx context.Context, in *ClusterEvictReq, opts ...grpc.CallOption) (*ClusterEvictResp, error)
		// app 相关
		AppAdd(ctx context.Context, in *AddClusterAppReq, opts ...grpc.CallOption) (*AddClusterAppResp, error)
		// 获取 app 详情信息
		AppDetail(ctx context.Context, in *ClusterAppDetailReq, opts ...grpc.CallOption) (*ClusterAppDetailResp, error)
		// 测试中间件是否正常。
		AppValidate(ctx context.Context, in *ClusterAppValidateReq, opts ...grpc.CallOption) (*ClusterAppValidateResp, error)
		// 获取某一个集群 app 列表
		AppOnClusterList(ctx context.Context, in *ClusterAppListReq, opts ...grpc.CallOption) (*ClusterAppListResp, error)
		// 通过集群以及apptype 获取默认app 的配置信息
		AppDefaultConfig(ctx context.Context, in *AppDefaultConfigReq, opts ...grpc.CallOption) (*AppDefaultConfigResp, error)
		// -----------------------项目表，记录项目信息-----------------------
		ProjectAdd(ctx context.Context, in *AddOnecProjectReq, opts ...grpc.CallOption) (*AddOnecProjectResp, error)
		ProjectUpdate(ctx context.Context, in *UpdateOnecProjectReq, opts ...grpc.CallOption) (*UpdateOnecProjectResp, error)
		ProjectDel(ctx context.Context, in *DelOnecProjectReq, opts ...grpc.CallOption) (*DelOnecProjectResp, error)
		ProjectGetById(ctx context.Context, in *GetOnecProjectByIdReq, opts ...grpc.CallOption) (*GetOnecProjectByIdResp, error)
		ProjectSearch(ctx context.Context, in *SearchOnecProjectReq, opts ...grpc.CallOption) (*SearchOnecProjectResp, error)
		ProjectSync(ctx context.Context, in *ProjectSyncReq, opts ...grpc.CallOption) (*ProjectSyncResp, error)
		// 同步所有项目配额
		ProjectAllSync(ctx context.Context, in *ProjectQuotaSyncReq, opts ...grpc.CallOption) (*ProjectQuotaSyncResp, error)
		// -----------------------项目管理员表，关联项目与用户的多对多关系-----------------------
		ProjectAdminAdd(ctx context.Context, in *AddOnecProjectAdminReq, opts ...grpc.CallOption) (*AddOnecProjectAdminResp, error)
		ProjectAdminGetByProjectId(ctx context.Context, in *GetOnecProjectAdminsByProjectIdReq, opts ...grpc.CallOption) (*GetOnecProjectAdminsByProjectIdResp, error)
		// 通过用户ID查询可用的项目
		ProjectGetByUserId(ctx context.Context, in *GetOnecProjectsByUserIdReq, opts ...grpc.CallOption) (*GetOnecProjectsByUserIdResp, error)
		// -----------------------项目集群配额表，记录项目配额信息-----------------------
		ProjectClusterAdd(ctx context.Context, in *AddOnecProjectClusterReq, opts ...grpc.CallOption) (*AddOnecProjectClusterResp, error)
		ProjectClusterUpdate(ctx context.Context, in *UpdateOnecProjectClusterReq, opts ...grpc.CallOption) (*UpdateOnecProjectClusterResp, error)
		ProjectClusterDel(ctx context.Context, in *DelOnecProjectClusterReq, opts ...grpc.CallOption) (*DelOnecProjectClusterResp, error)
		ProjectClusterGetById(ctx context.Context, in *GetOnecProjectClusterByIdReq, opts ...grpc.CallOption) (*GetOnecProjectClusterByIdResp, error)
		ProjectClusterSearch(ctx context.Context, in *SearchOnecProjectClusterReq, opts ...grpc.CallOption) (*SearchOnecProjectClusterResp, error)
		// 同步项目集群配额 同步就是计算各种资源的 使用量，更新表
		ProjectClusterSync(ctx context.Context, in *ProjectClusterSyncReq, opts ...grpc.CallOption) (*ProjectClusterSyncResp, error)
		// -----------------------项目工作空间表，记录项目工作空间信息-----------------------
		ProjectWorkspaceAdd(ctx context.Context, in *AddOnecProjectWorkspaceReq, opts ...grpc.CallOption) (*AddOnecProjectWorkspaceResp, error)
		ProjectWorkspaceUpdate(ctx context.Context, in *UpdateOnecProjectWorkspaceReq, opts ...grpc.CallOption) (*UpdateOnecProjectWorkspaceResp, error)
		ProjectWorkspaceDel(ctx context.Context, in *DelOnecProjectWorkspaceReq, opts ...grpc.CallOption) (*DelOnecProjectWorkspaceResp, error)
		ProjectWorkspaceGetById(ctx context.Context, in *GetOnecProjectWorkspaceByIdReq, opts ...grpc.CallOption) (*GetOnecProjectWorkspaceByIdResp, error)
		ProjectWorkspaceSearch(ctx context.Context, in *SearchOnecProjectWorkspaceReq, opts ...grpc.CallOption) (*SearchOnecProjectWorkspaceResp, error)
		ProjectWorkspaceSync(ctx context.Context, in *ProjectWorkspaceSyncReq, opts ...grpc.CallOption) (*ProjectWorkspaceSyncResp, error)
		// 项目的应用表相关rpc
		ApplicationAdd(ctx context.Context, in *AddOnecProjectApplicationReq, opts ...grpc.CallOption) (*AddOnecProjectApplicationResp, error)
		ApplicationUpdate(ctx context.Context, in *UpdateOnecProjectApplicationReq, opts ...grpc.CallOption) (*UpdateOnecProjectApplicationResp, error)
		ApplicationDel(ctx context.Context, in *DelOnecProjectApplicationReq, opts ...grpc.CallOption) (*DelOnecProjectApplicationResp, error)
		ApplicationGetById(ctx context.Context, in *GetOnecProjectApplicationByIdReq, opts ...grpc.CallOption) (*GetOnecProjectApplicationByIdResp, error)
		ApplicationSearch(ctx context.Context, in *SearchOnecProjectApplicationReq, opts ...grpc.CallOption) (*SearchOnecProjectApplicationResp, error)
		// 项目的应用表 版本相关 rpc
		VersionAdd(ctx context.Context, in *AddOnecProjectVersionReq, opts ...grpc.CallOption) (*AddOnecProjectVersionResp, error)
		VersionDel(ctx context.Context, in *DelOnecProjectVersionReq, opts ...grpc.CallOption) (*DelOnecProjectVersionResp, error)
		VersionSearch(ctx context.Context, in *SearchOnecProjectVersionReq, opts ...grpc.CallOption) (*SearchOnecProjectVersionResp, error)
		// 获取版本detailinfo
		VersionDetail(ctx context.Context, in *GetOnecProjectVersionDetailReq, opts ...grpc.CallOption) (*GetOnecProjectVersionDetailResp, error)
		// -----------------------资源操作审计日志表，记录所有资源控制器操作-----------------------
		ProjectAuditLogAdd(ctx context.Context, in *AddOnecProjectAuditLogReq, opts ...grpc.CallOption) (*AddOnecProjectAuditLogResp, error)
		ProjectAuditLogDel(ctx context.Context, in *DelOnecProjectAuditLogReq, opts ...grpc.CallOption) (*DelOnecProjectAuditLogResp, error)
		ProjectAuditLogSearch(ctx context.Context, in *SearchOnecProjectAuditLogReq, opts ...grpc.CallOption) (*SearchOnecProjectAuditLogResp, error)
		// 批量删除
		ProjectAuditLogBatchDel(ctx context.Context, in *BatchDelOnecProjectAuditLogReq, opts ...grpc.CallOption) (*BatchDelOnecProjectAuditLogResp, error)
		// 删除指定天数之前的数据
		ProjectAuditLogDelBeforeDays(ctx context.Context, in *DelOnecProjectAuditLogBeforeDaysReq, opts ...grpc.CallOption) (*DelOnecProjectAuditLogBeforeDaysResp, error)
		// 迁移相关
		SchedulePlanSave(ctx context.Context, in *SaveSchedulePlanReq, opts ...grpc.CallOption) (*SaveSchedulePlanResp, error)
		SchedulePlanUpdateStatus(ctx context.Context, in *UpdateSchedulePlanStatusReq, opts ...grpc.CallOption) (*UpdateSchedulePlanStatusResp, error)
		MigrateWorkspace(ctx context.Context, in *MigrateWorkspaceReq, opts ...grpc.CallOption) (*MigrateWorkspaceResp, error)
		// 告警仪表盘
		AlertDashboardOverview(ctx context.Context, in *GetAlertOverviewReq, opts ...grpc.CallOption) (*GetAlertOverviewResp, error)
		// 获取告警级别统计
		AlertDashboardSeverityStats(ctx context.Context, in *GetAlertSeverityStatsReq, opts ...grpc.CallOption) (*GetAlertSeverityStatsResp, error)
		// 获取告警趋势分析
		AlertDashboardTrend(ctx context.Context, in *GetAlertTrendReq, opts ...grpc.CallOption) (*GetAlertTrendResp, error)
		// 获取告警维度统计
		AlertDashboardDimensionStats(ctx context.Context, in *GetAlertDimensionStatsReq, opts ...grpc.CallOption) (*GetAlertDimensionStatsResp, error)
		// 获取告警排行榜
		AlertDashboardTopRanking(ctx context.Context, in *GetAlertTopRankingReq, opts ...grpc.CallOption) (*GetAlertTopRankingResp, error)
		// 获取告警实时状态
		AlertDashboardRealtimeStatus(ctx context.Context, in *GetAlertRealtimeStatusReq, opts ...grpc.CallOption) (*GetAlertRealtimeStatusResp, error)
		// 获取告警汇总报告
		AlertDashboardSummaryReport(ctx context.Context, in *GetAlertSummaryReportReq, opts ...grpc.CallOption) (*GetAlertSummaryReportResp, error)
		// 集群资源仪表盘
		GetResourceDashboardSummary(ctx context.Context, in *ResourceDashboardSummaryReq, opts ...grpc.CallOption) (*ResourceDashboardSummaryResp, error)
		// 获取集群资源排行
		GetClusterResourceRanking(ctx context.Context, in *ClusterResourceRankingReq, opts ...grpc.CallOption) (*ClusterResourceRankingResp, error)
		// 获取项目资源排行
		GetProjectResourceRanking(ctx context.Context, in *ProjectResourceRankingReq, opts ...grpc.CallOption) (*ProjectResourceRankingResp, error)
		// 获取工作空间资源排行
		GetWorkspaceResourceRanking(ctx context.Context, in *WorkspaceResourceRankingReq, opts ...grpc.CallOption) (*WorkspaceResourceRankingResp, error)
		// -----------------------收费配置表-----------------------
		OnecBillingPriceConfigAdd(ctx context.Context, in *OnecBillingPriceConfigAddReq, opts ...grpc.CallOption) (*OnecBillingPriceConfigAddResp, error)
		OnecBillingPriceConfigUpdate(ctx context.Context, in *OnecBillingPriceConfigUpdateReq, opts ...grpc.CallOption) (*OnecBillingPriceConfigUpdateResp, error)
		OnecBillingPriceConfigDel(ctx context.Context, in *OnecBillingPriceConfigDelReq, opts ...grpc.CallOption) (*OnecBillingPriceConfigDelResp, error)
		OnecBillingPriceConfigGetById(ctx context.Context, in *OnecBillingPriceConfigGetByIdReq, opts ...grpc.CallOption) (*OnecBillingPriceConfigGetByIdResp, error)
		OnecBillingPriceConfigSearch(ctx context.Context, in *OnecBillingPriceConfigSearchReq, opts ...grpc.CallOption) (*OnecBillingPriceConfigSearchResp, error)
		// -----------------------计费配置绑定表-----------------------
		OnecBillingConfigBindingAdd(ctx context.Context, in *OnecBillingConfigBindingAddReq, opts ...grpc.CallOption) (*OnecBillingConfigBindingAddResp, error)
		OnecBillingConfigBindingUpdate(ctx context.Context, in *OnecBillingConfigBindingUpdateReq, opts ...grpc.CallOption) (*OnecBillingConfigBindingUpdateResp, error)
		OnecBillingConfigBindingDel(ctx context.Context, in *OnecBillingConfigBindingDelReq, opts ...grpc.CallOption) (*OnecBillingConfigBindingDelResp, error)
		OnecBillingConfigBindingGet(ctx context.Context, in *OnecBillingConfigBindingGetReq, opts ...grpc.CallOption) (*OnecBillingConfigBindingGetResp, error)
		// -----------------------账单仪表盘-----------------------
		OnecBillingDashboardStats(ctx context.Context, in *OnecBillingDashboardStatsReq, opts ...grpc.CallOption) (*OnecBillingDashboardStatsResp, error)
		OnecBillingCostComposition(ctx context.Context, in *OnecBillingCostCompositionReq, opts ...grpc.CallOption) (*OnecBillingCostCompositionResp, error)
		OnecBillingCostTrend(ctx context.Context, in *OnecBillingCostTrendReq, opts ...grpc.CallOption) (*OnecBillingCostTrendResp, error)
		OnecBillingProjectTop(ctx context.Context, in *OnecBillingProjectTopReq, opts ...grpc.CallOption) (*OnecBillingProjectTopResp, error)
		OnecBillingClusterTop(ctx context.Context, in *OnecBillingClusterTopReq, opts ...grpc.CallOption) (*OnecBillingClusterTopResp, error)
		// -----------------------账单中心-----------------------
		OnecBillingStatementSearch(ctx context.Context, in *OnecBillingStatementSearchReq, opts ...grpc.CallOption) (*OnecBillingStatementSearchResp, error)
		OnecBillingStatementDel(ctx context.Context, in *OnecBillingStatementDelReq, opts ...grpc.CallOption) (*OnecBillingStatementDelResp, error)
		OnecBillingStatementBatchDel(ctx context.Context, in *OnecBillingStatementBatchDelReq, opts ...grpc.CallOption) (*OnecBillingStatementBatchDelResp, error)
		// 立即生成账单
		OnecBillingStatementGenerate(ctx context.Context, in *OnecBillingStatementGenerateReq, opts ...grpc.CallOption) (*OnecBillingStatementGenerateResp, error)
		// 生成所有账单
		OnecBillingStatementGenerateAll(ctx context.Context, in *OnecBillingStatementGenerateAllReq, opts ...grpc.CallOption) (*OnecBillingStatementGenerateAllResp, error)
		// 获取Alertmanager配置
		GetAlertmanagerConfig(ctx context.Context, in *GetAlertmanagerConfigReq, opts ...grpc.CallOption) (*GetAlertmanagerConfigResp, error)
		// 获取Prometheus配置
		GetPrometheusConfig(ctx context.Context, in *GetPrometheusConfigReq, opts ...grpc.CallOption) (*GetPrometheusConfigResp, error)
		// 配置Alertmanager
		SetAlertmanagerConfig(ctx context.Context, in *SetAlertmanagerConfigReq, opts ...grpc.CallOption) (*SetAlertmanagerConfigResp, error)
		// 按集群拉取 onec_cluster_node_energy（已删过滤），供工作负载「能耗感知」软偏好
		ListOnecClusterNodeEnergy(ctx context.Context, in *ListOnecClusterNodeEnergyReq, opts ...grpc.CallOption) (*ListOnecClusterNodeEnergyResp, error)
	}

	defaultManagerService struct {
		cli zrpc.Client
	}
)

func NewManagerService(cli zrpc.Client) ManagerService {
	return &defaultManagerService{
		cli: cli,
	}
}

// //通过 clusterUuid 和 namespace 获取 详情信息
func (m *defaultManagerService) GetClusterNsDetail(ctx context.Context, in *GetClusterNsDetailReq, opts ...grpc.CallOption) (*GetClusterNsDetailResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.GetClusterNsDetail(ctx, in, opts...)
}

// 获取某一个集群的所有ns
func (m *defaultManagerService) GetClusterNs(ctx context.Context, in *GetClusterNsReq, opts ...grpc.CallOption) (*GetClusterNsResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.GetClusterNs(ctx, in, opts...)
}

// -----------------------告警实例表-----------------------
func (m *defaultManagerService) AlertInstancesDel(ctx context.Context, in *DelAlertInstancesReq, opts ...grpc.CallOption) (*DelAlertInstancesResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.AlertInstancesDel(ctx, in, opts...)
}

func (m *defaultManagerService) AlertInstancesByIdGet(ctx context.Context, in *GetAlertInstancesByIdReq, opts ...grpc.CallOption) (*GetAlertInstancesByIdResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.AlertInstancesByIdGet(ctx, in, opts...)
}

func (m *defaultManagerService) AlertInstancesSearch(ctx context.Context, in *SearchAlertInstancesReq, opts ...grpc.CallOption) (*SearchAlertInstancesResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.AlertInstancesSearch(ctx, in, opts...)
}

func (m *defaultManagerService) AlertInstancesBatchDel(ctx context.Context, in *BatchDelAlertInstancesReq, opts ...grpc.CallOption) (*BatchDelAlertInstancesResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.AlertInstancesBatchDel(ctx, in, opts...)
}

// -----------------------告警规则表-----------------------
func (m *defaultManagerService) AlertRuleFileAdd(ctx context.Context, in *AddAlertRuleFileReq, opts ...grpc.CallOption) (*AddAlertRuleFileResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.AlertRuleFileAdd(ctx, in, opts...)
}

func (m *defaultManagerService) AlertRuleFileUpdate(ctx context.Context, in *UpdateAlertRuleFileReq, opts ...grpc.CallOption) (*UpdateAlertRuleFileResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.AlertRuleFileUpdate(ctx, in, opts...)
}

func (m *defaultManagerService) AlertRuleFileDel(ctx context.Context, in *DelAlertRuleFileReq, opts ...grpc.CallOption) (*DelAlertRuleFileResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.AlertRuleFileDel(ctx, in, opts...)
}

func (m *defaultManagerService) AlertRuleFileGetById(ctx context.Context, in *GetAlertRuleFileByIdReq, opts ...grpc.CallOption) (*GetAlertRuleFileByIdResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.AlertRuleFileGetById(ctx, in, opts...)
}

func (m *defaultManagerService) AlertRuleFileSearch(ctx context.Context, in *SearchAlertRuleFileReq, opts ...grpc.CallOption) (*SearchAlertRuleFileResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.AlertRuleFileSearch(ctx, in, opts...)
}

func (m *defaultManagerService) AlertRuleFileList(ctx context.Context, in *ListAlertRuleFileReq, opts ...grpc.CallOption) (*ListAlertRuleFileResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.AlertRuleFileList(ctx, in, opts...)
}

// ===================== 告警规则分组表 =====================
func (m *defaultManagerService) AlertRuleGroupAdd(ctx context.Context, in *AddAlertRuleGroupReq, opts ...grpc.CallOption) (*AddAlertRuleGroupResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.AlertRuleGroupAdd(ctx, in, opts...)
}

func (m *defaultManagerService) AlertRuleGroupUpdate(ctx context.Context, in *UpdateAlertRuleGroupReq, opts ...grpc.CallOption) (*UpdateAlertRuleGroupResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.AlertRuleGroupUpdate(ctx, in, opts...)
}

func (m *defaultManagerService) AlertRuleGroupDel(ctx context.Context, in *DelAlertRuleGroupReq, opts ...grpc.CallOption) (*DelAlertRuleGroupResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.AlertRuleGroupDel(ctx, in, opts...)
}

func (m *defaultManagerService) AlertRuleGroupGetById(ctx context.Context, in *GetAlertRuleGroupByIdReq, opts ...grpc.CallOption) (*GetAlertRuleGroupByIdResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.AlertRuleGroupGetById(ctx, in, opts...)
}

func (m *defaultManagerService) AlertRuleGroupSearch(ctx context.Context, in *SearchAlertRuleGroupReq, opts ...grpc.CallOption) (*SearchAlertRuleGroupResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.AlertRuleGroupSearch(ctx, in, opts...)
}

func (m *defaultManagerService) AlertRuleGroupList(ctx context.Context, in *ListAlertRuleGroupReq, opts ...grpc.CallOption) (*ListAlertRuleGroupResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.AlertRuleGroupList(ctx, in, opts...)
}

// ===================== 告警规则表 =====================
func (m *defaultManagerService) AlertRuleAdd(ctx context.Context, in *AddAlertRuleReq, opts ...grpc.CallOption) (*AddAlertRuleResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.AlertRuleAdd(ctx, in, opts...)
}

func (m *defaultManagerService) AlertRuleUpdate(ctx context.Context, in *UpdateAlertRuleReq, opts ...grpc.CallOption) (*UpdateAlertRuleResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.AlertRuleUpdate(ctx, in, opts...)
}

func (m *defaultManagerService) AlertRuleDel(ctx context.Context, in *DelAlertRuleReq, opts ...grpc.CallOption) (*DelAlertRuleResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.AlertRuleDel(ctx, in, opts...)
}

func (m *defaultManagerService) AlertRuleGetById(ctx context.Context, in *GetAlertRuleByIdReq, opts ...grpc.CallOption) (*GetAlertRuleByIdResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.AlertRuleGetById(ctx, in, opts...)
}

func (m *defaultManagerService) AlertRuleSearch(ctx context.Context, in *SearchAlertRuleReq, opts ...grpc.CallOption) (*SearchAlertRuleResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.AlertRuleSearch(ctx, in, opts...)
}

func (m *defaultManagerService) AlertRuleBatchDel(ctx context.Context, in *BatchDelAlertRuleReq, opts ...grpc.CallOption) (*BatchDelAlertRuleResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.AlertRuleBatchDel(ctx, in, opts...)
}

// ===================== 导入/导出/部署 =====================
func (m *defaultManagerService) AlertRulesBatchImport(ctx context.Context, in *BatchImportAlertRulesReq, opts ...grpc.CallOption) (*BatchImportAlertRulesResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.AlertRulesBatchImport(ctx, in, opts...)
}

func (m *defaultManagerService) AlertRulesBatchExport(ctx context.Context, in *BatchExportAlertRulesReq, opts ...grpc.CallOption) (*BatchExportAlertRulesResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.AlertRulesBatchExport(ctx, in, opts...)
}

func (m *defaultManagerService) AlertRulesDeploy(ctx context.Context, in *DeployAlertRulesReq, opts ...grpc.CallOption) (*DeployAlertRulesResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.AlertRulesDeploy(ctx, in, opts...)
}

func (m *defaultManagerService) AlertRulesPreviewYaml(ctx context.Context, in *PreviewAlertRulesYamlReq, opts ...grpc.CallOption) (*PreviewAlertRulesYamlResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.AlertRulesPreviewYaml(ctx, in, opts...)
}

func (m *defaultManagerService) AlertRulesExportAll(ctx context.Context, in *ExportAllAlertRulesReq, opts ...grpc.CallOption) (*ExportAllAlertRulesResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.AlertRulesExportAll(ctx, in, opts...)
}

func (m *defaultManagerService) AlertRulesDeployAll(ctx context.Context, in *DeployAllAlertRulesReq, opts ...grpc.CallOption) (*DeployAllAlertRulesResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.AlertRulesDeployAll(ctx, in, opts...)
}

// ===================== 树形结构 =====================
func (m *defaultManagerService) AlertRuleTreeGet(ctx context.Context, in *GetAlertRuleTreeReq, opts ...grpc.CallOption) (*GetAlertRuleTreeResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.AlertRuleTreeGet(ctx, in, opts...)
}

// ===================== Alertmanager Webhook =====================
func (m *defaultManagerService) ReceiveAlertmanagerWebhook(ctx context.Context, in *ReceiveAlertmanagerWebhookReq, opts ...grpc.CallOption) (*ReceiveAlertmanagerWebhookResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.ReceiveAlertmanagerWebhook(ctx, in, opts...)
}

// 获取集群默认域名后缀
func (m *defaultManagerService) GetClusterDefaultDomainSuffix(ctx context.Context, in *GetClusterDefaultDomainSuffixReq, opts ...grpc.CallOption) (*GetClusterDefaultDomainSuffixResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.GetClusterDefaultDomainSuffix(ctx, in, opts...)
}

// 获取集群 node or master lb 列表
func (m *defaultManagerService) GetClusterLbList(ctx context.Context, in *GetClusterLbListReq, opts ...grpc.CallOption) (*GetClusterLbListResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.GetClusterLbList(ctx, in, opts...)
}

// 通过集群uuid获取集群认证信息
func (m *defaultManagerService) GetClusterAuthInfo(ctx context.Context, in *GetClusterAuthInfoReq, opts ...grpc.CallOption) (*GetClusterAuthInfoResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.GetClusterAuthInfo(ctx, in, opts...)
}

// 修改集群认证信息
func (m *defaultManagerService) ClusterUpdateAuthInfo(ctx context.Context, in *ClusterUpdateAuthInfoReq, opts ...grpc.CallOption) (*ClusterUpdateAuthInfoResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.ClusterUpdateAuthInfo(ctx, in, opts...)
}

// 修改集群图标
func (m *defaultManagerService) ClusterUpdateIcon(ctx context.Context, in *ClusterUpdateAvatarReq, opts ...grpc.CallOption) (*ClusterUpdateAvatarResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.ClusterUpdateIcon(ctx, in, opts...)
}

// 测试集群连通性
func (m *defaultManagerService) ClusterTestConnect(ctx context.Context, in *ClusterTestConnectReq, opts ...grpc.CallOption) (*ClusterTestConnectResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.ClusterTestConnect(ctx, in, opts...)
}

// 删除集群
func (m *defaultManagerService) ClusterDelete(ctx context.Context, in *DeleteClusterReq, opts ...grpc.CallOption) (*DeleteClusterResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.ClusterDelete(ctx, in, opts...)
}

// 修改集群
func (m *defaultManagerService) ClusterUpdate(ctx context.Context, in *UpdateClusterReq, opts ...grpc.CallOption) (*UpdateClusterResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.ClusterUpdate(ctx, in, opts...)
}

func (m *defaultManagerService) ClusterSearch(ctx context.Context, in *SearchClusterReq, opts ...grpc.CallOption) (*SearchClusterResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.ClusterSearch(ctx, in, opts...)
}

func (m *defaultManagerService) ClusterAdd(ctx context.Context, in *AddClusterRequest, opts ...grpc.CallOption) (*AddClusterResponse, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.ClusterAdd(ctx, in, opts...)
}

// 获取 某一个集群 ingressDomain 列表
func (m *defaultManagerService) GetClusterIngressDomainList(ctx context.Context, in *GetClusterDomainListReq, opts ...grpc.CallOption) (*GetClusterDomainListResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.GetClusterIngressDomainList(ctx, in, opts...)
}

func (m *defaultManagerService) GetClusterNetwork(ctx context.Context, in *GetClusterNetworkReq, opts ...grpc.CallOption) (*GetClusterNetworkResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.GetClusterNetwork(ctx, in, opts...)
}

func (m *defaultManagerService) UpdateClusterStorageCapacity(ctx context.Context, in *UpdateClusterStorageCapacityReq, opts ...grpc.CallOption) (*UpdateClusterStorageCapacityResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.UpdateClusterStorageCapacity(ctx, in, opts...)
}

// 获取集群详情
func (m *defaultManagerService) ClusterDetail(ctx context.Context, in *ClusterDetailReq, opts ...grpc.CallOption) (*ClusterDetailResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.ClusterDetail(ctx, in, opts...)
}

func (m *defaultManagerService) ClusterSync(ctx context.Context, in *SyncClusterReq, opts ...grpc.CallOption) (*SyncClusterResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.ClusterSync(ctx, in, opts...)
}

func (m *defaultManagerService) ClusterAuthInfo(ctx context.Context, in *ClusterAuthInfoReq, opts ...grpc.CallOption) (*ClusterAuthInfoResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.ClusterAuthInfo(ctx, in, opts...)
}

// 集群资源
func (m *defaultManagerService) ClusterResourceInfo(ctx context.Context, in *ClusterResourceInfoReq, opts ...grpc.CallOption) (*ClusterResourceInfoResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.ClusterResourceInfo(ctx, in, opts...)
}

// 同步某一个集群资源
func (m *defaultManagerService) ClusterResourceSync(ctx context.Context, in *ClusterResourceSyncReq, opts ...grpc.CallOption) (*ClusterResourceSyncResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.ClusterResourceSync(ctx, in, opts...)
}

func (m *defaultManagerService) ClusterSyncAll(ctx context.Context, in *ClusterSyncAllReq, opts ...grpc.CallOption) (*ClusterSyncAllResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.ClusterSyncAll(ctx, in, opts...)
}

// node 相关
func (m *defaultManagerService) NodeInfo(ctx context.Context, in *ClusterNodeInfoReq, opts ...grpc.CallOption) (*ClusterNodeInfoResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.NodeInfo(ctx, in, opts...)
}

func (m *defaultManagerService) NodeDetail(ctx context.Context, in *ClusterNodeDetailReq, opts ...grpc.CallOption) (*OnecClusterNodeResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.NodeDetail(ctx, in, opts...)
}

// 获取 node  yaml describe
func (m *defaultManagerService) NodeYamlDescribe(ctx context.Context, in *ClusterNodeYamlDescribeReq, opts ...grpc.CallOption) (*ClusterNodeYamlDescribeResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.NodeYamlDescribe(ctx, in, opts...)
}

// labels 相关
func (m *defaultManagerService) NodeLabelsList(ctx context.Context, in *ClusterNodeLabelsListReq, opts ...grpc.CallOption) (*ClusterNodeLabelsListResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.NodeLabelsList(ctx, in, opts...)
}

// 添加 labels
func (m *defaultManagerService) NodeAddLabels(ctx context.Context, in *ClusterNodeAddLabelsReq, opts ...grpc.CallOption) (*ClusterNodeDisableResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.NodeAddLabels(ctx, in, opts...)
}

// 删除 labels
func (m *defaultManagerService) NodeDeleteLabels(ctx context.Context, in *ClusterNodeDeleteLabelsReq, opts ...grpc.CallOption) (*ClusterNodeDisableResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.NodeDeleteLabels(ctx, in, opts...)
}

// 注解相关
func (m *defaultManagerService) NodeAddAnnotations(ctx context.Context, in *ClusterNodeAddAnnotationsReq, opts ...grpc.CallOption) (*ClusterNodeAddAnnotationsResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.NodeAddAnnotations(ctx, in, opts...)
}

// 删除注解
func (m *defaultManagerService) NodeDeleteAnnotations(ctx context.Context, in *ClusterNodeDeleteAnnotationsReq, opts ...grpc.CallOption) (*ClusterNodeDeleteAnnotationsResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.NodeDeleteAnnotations(ctx, in, opts...)
}

// 获取注解列表
func (m *defaultManagerService) NodeAnnotationsList(ctx context.Context, in *ClusterNodeAnnotationsListReq, opts ...grpc.CallOption) (*ClusterNodeAnnotationsListResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.NodeAnnotationsList(ctx, in, opts...)
}

// 污点相关
func (m *defaultManagerService) NodeDisable(ctx context.Context, in *ClusterNodeDisableReq, opts ...grpc.CallOption) (*ClusterNodeDisableResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.NodeDisable(ctx, in, opts...)
}

// 添加污点
func (m *defaultManagerService) NodeAddTaint(ctx context.Context, in *ClusterNodeAddTaintReq, opts ...grpc.CallOption) (*ClusterNodeAddTaintResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.NodeAddTaint(ctx, in, opts...)
}

// 删除污点
func (m *defaultManagerService) NodeDeleteTaint(ctx context.Context, in *ClusterNodeDeleteTaintReq, opts ...grpc.CallOption) (*ClusterNodeDisableResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.NodeDeleteTaint(ctx, in, opts...)
}

// 获取污点列表
func (m *defaultManagerService) NodeTaintList(ctx context.Context, in *ClusterNodeTaintsListReq, opts ...grpc.CallOption) (*ClusterNodeTaintsListResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.NodeTaintList(ctx, in, opts...)
}

// 驱逐
func (m *defaultManagerService) NodeEvict(ctx context.Context, in *ClusterEvictReq, opts ...grpc.CallOption) (*ClusterEvictResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.NodeEvict(ctx, in, opts...)
}

// app 相关
func (m *defaultManagerService) AppAdd(ctx context.Context, in *AddClusterAppReq, opts ...grpc.CallOption) (*AddClusterAppResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.AppAdd(ctx, in, opts...)
}

// 获取 app 详情信息
func (m *defaultManagerService) AppDetail(ctx context.Context, in *ClusterAppDetailReq, opts ...grpc.CallOption) (*ClusterAppDetailResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.AppDetail(ctx, in, opts...)
}

// 测试中间件是否正常。
func (m *defaultManagerService) AppValidate(ctx context.Context, in *ClusterAppValidateReq, opts ...grpc.CallOption) (*ClusterAppValidateResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.AppValidate(ctx, in, opts...)
}

// 获取某一个集群 app 列表
func (m *defaultManagerService) AppOnClusterList(ctx context.Context, in *ClusterAppListReq, opts ...grpc.CallOption) (*ClusterAppListResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.AppOnClusterList(ctx, in, opts...)
}

// 通过集群以及apptype 获取默认app 的配置信息
func (m *defaultManagerService) AppDefaultConfig(ctx context.Context, in *AppDefaultConfigReq, opts ...grpc.CallOption) (*AppDefaultConfigResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.AppDefaultConfig(ctx, in, opts...)
}

// -----------------------项目表，记录项目信息-----------------------
func (m *defaultManagerService) ProjectAdd(ctx context.Context, in *AddOnecProjectReq, opts ...grpc.CallOption) (*AddOnecProjectResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.ProjectAdd(ctx, in, opts...)
}

func (m *defaultManagerService) ProjectUpdate(ctx context.Context, in *UpdateOnecProjectReq, opts ...grpc.CallOption) (*UpdateOnecProjectResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.ProjectUpdate(ctx, in, opts...)
}

func (m *defaultManagerService) ProjectDel(ctx context.Context, in *DelOnecProjectReq, opts ...grpc.CallOption) (*DelOnecProjectResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.ProjectDel(ctx, in, opts...)
}

func (m *defaultManagerService) ProjectGetById(ctx context.Context, in *GetOnecProjectByIdReq, opts ...grpc.CallOption) (*GetOnecProjectByIdResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.ProjectGetById(ctx, in, opts...)
}

func (m *defaultManagerService) ProjectSearch(ctx context.Context, in *SearchOnecProjectReq, opts ...grpc.CallOption) (*SearchOnecProjectResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.ProjectSearch(ctx, in, opts...)
}

func (m *defaultManagerService) ProjectSync(ctx context.Context, in *ProjectSyncReq, opts ...grpc.CallOption) (*ProjectSyncResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.ProjectSync(ctx, in, opts...)
}

// 同步所有项目配额
func (m *defaultManagerService) ProjectAllSync(ctx context.Context, in *ProjectQuotaSyncReq, opts ...grpc.CallOption) (*ProjectQuotaSyncResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.ProjectAllSync(ctx, in, opts...)
}

// -----------------------项目管理员表，关联项目与用户的多对多关系-----------------------
func (m *defaultManagerService) ProjectAdminAdd(ctx context.Context, in *AddOnecProjectAdminReq, opts ...grpc.CallOption) (*AddOnecProjectAdminResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.ProjectAdminAdd(ctx, in, opts...)
}

func (m *defaultManagerService) ProjectAdminGetByProjectId(ctx context.Context, in *GetOnecProjectAdminsByProjectIdReq, opts ...grpc.CallOption) (*GetOnecProjectAdminsByProjectIdResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.ProjectAdminGetByProjectId(ctx, in, opts...)
}

// 通过用户ID查询可用的项目
func (m *defaultManagerService) ProjectGetByUserId(ctx context.Context, in *GetOnecProjectsByUserIdReq, opts ...grpc.CallOption) (*GetOnecProjectsByUserIdResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.ProjectGetByUserId(ctx, in, opts...)
}

// -----------------------项目集群配额表，记录项目配额信息-----------------------
func (m *defaultManagerService) ProjectClusterAdd(ctx context.Context, in *AddOnecProjectClusterReq, opts ...grpc.CallOption) (*AddOnecProjectClusterResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.ProjectClusterAdd(ctx, in, opts...)
}

func (m *defaultManagerService) ProjectClusterUpdate(ctx context.Context, in *UpdateOnecProjectClusterReq, opts ...grpc.CallOption) (*UpdateOnecProjectClusterResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.ProjectClusterUpdate(ctx, in, opts...)
}

func (m *defaultManagerService) ProjectClusterDel(ctx context.Context, in *DelOnecProjectClusterReq, opts ...grpc.CallOption) (*DelOnecProjectClusterResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.ProjectClusterDel(ctx, in, opts...)
}

func (m *defaultManagerService) ProjectClusterGetById(ctx context.Context, in *GetOnecProjectClusterByIdReq, opts ...grpc.CallOption) (*GetOnecProjectClusterByIdResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.ProjectClusterGetById(ctx, in, opts...)
}

func (m *defaultManagerService) ProjectClusterSearch(ctx context.Context, in *SearchOnecProjectClusterReq, opts ...grpc.CallOption) (*SearchOnecProjectClusterResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.ProjectClusterSearch(ctx, in, opts...)
}

// 同步项目集群配额 同步就是计算各种资源的 使用量，更新表
func (m *defaultManagerService) ProjectClusterSync(ctx context.Context, in *ProjectClusterSyncReq, opts ...grpc.CallOption) (*ProjectClusterSyncResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.ProjectClusterSync(ctx, in, opts...)
}

// -----------------------项目工作空间表，记录项目工作空间信息-----------------------
func (m *defaultManagerService) ProjectWorkspaceAdd(ctx context.Context, in *AddOnecProjectWorkspaceReq, opts ...grpc.CallOption) (*AddOnecProjectWorkspaceResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.ProjectWorkspaceAdd(ctx, in, opts...)
}

func (m *defaultManagerService) ProjectWorkspaceUpdate(ctx context.Context, in *UpdateOnecProjectWorkspaceReq, opts ...grpc.CallOption) (*UpdateOnecProjectWorkspaceResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.ProjectWorkspaceUpdate(ctx, in, opts...)
}

func (m *defaultManagerService) ProjectWorkspaceDel(ctx context.Context, in *DelOnecProjectWorkspaceReq, opts ...grpc.CallOption) (*DelOnecProjectWorkspaceResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.ProjectWorkspaceDel(ctx, in, opts...)
}

func (m *defaultManagerService) ProjectWorkspaceGetById(ctx context.Context, in *GetOnecProjectWorkspaceByIdReq, opts ...grpc.CallOption) (*GetOnecProjectWorkspaceByIdResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.ProjectWorkspaceGetById(ctx, in, opts...)
}

func (m *defaultManagerService) ProjectWorkspaceSearch(ctx context.Context, in *SearchOnecProjectWorkspaceReq, opts ...grpc.CallOption) (*SearchOnecProjectWorkspaceResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.ProjectWorkspaceSearch(ctx, in, opts...)
}

func (m *defaultManagerService) ProjectWorkspaceSync(ctx context.Context, in *ProjectWorkspaceSyncReq, opts ...grpc.CallOption) (*ProjectWorkspaceSyncResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.ProjectWorkspaceSync(ctx, in, opts...)
}

// 项目的应用表相关rpc
func (m *defaultManagerService) ApplicationAdd(ctx context.Context, in *AddOnecProjectApplicationReq, opts ...grpc.CallOption) (*AddOnecProjectApplicationResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.ApplicationAdd(ctx, in, opts...)
}

func (m *defaultManagerService) ApplicationUpdate(ctx context.Context, in *UpdateOnecProjectApplicationReq, opts ...grpc.CallOption) (*UpdateOnecProjectApplicationResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.ApplicationUpdate(ctx, in, opts...)
}

func (m *defaultManagerService) ApplicationDel(ctx context.Context, in *DelOnecProjectApplicationReq, opts ...grpc.CallOption) (*DelOnecProjectApplicationResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.ApplicationDel(ctx, in, opts...)
}

func (m *defaultManagerService) ApplicationGetById(ctx context.Context, in *GetOnecProjectApplicationByIdReq, opts ...grpc.CallOption) (*GetOnecProjectApplicationByIdResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.ApplicationGetById(ctx, in, opts...)
}

func (m *defaultManagerService) ApplicationSearch(ctx context.Context, in *SearchOnecProjectApplicationReq, opts ...grpc.CallOption) (*SearchOnecProjectApplicationResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.ApplicationSearch(ctx, in, opts...)
}

// 项目的应用表 版本相关 rpc
func (m *defaultManagerService) VersionAdd(ctx context.Context, in *AddOnecProjectVersionReq, opts ...grpc.CallOption) (*AddOnecProjectVersionResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.VersionAdd(ctx, in, opts...)
}

func (m *defaultManagerService) VersionDel(ctx context.Context, in *DelOnecProjectVersionReq, opts ...grpc.CallOption) (*DelOnecProjectVersionResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.VersionDel(ctx, in, opts...)
}

func (m *defaultManagerService) VersionSearch(ctx context.Context, in *SearchOnecProjectVersionReq, opts ...grpc.CallOption) (*SearchOnecProjectVersionResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.VersionSearch(ctx, in, opts...)
}

// 获取版本detailinfo
func (m *defaultManagerService) VersionDetail(ctx context.Context, in *GetOnecProjectVersionDetailReq, opts ...grpc.CallOption) (*GetOnecProjectVersionDetailResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.VersionDetail(ctx, in, opts...)
}

// -----------------------资源操作审计日志表，记录所有资源控制器操作-----------------------
func (m *defaultManagerService) ProjectAuditLogAdd(ctx context.Context, in *AddOnecProjectAuditLogReq, opts ...grpc.CallOption) (*AddOnecProjectAuditLogResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.ProjectAuditLogAdd(ctx, in, opts...)
}

func (m *defaultManagerService) ProjectAuditLogDel(ctx context.Context, in *DelOnecProjectAuditLogReq, opts ...grpc.CallOption) (*DelOnecProjectAuditLogResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.ProjectAuditLogDel(ctx, in, opts...)
}

func (m *defaultManagerService) ProjectAuditLogSearch(ctx context.Context, in *SearchOnecProjectAuditLogReq, opts ...grpc.CallOption) (*SearchOnecProjectAuditLogResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.ProjectAuditLogSearch(ctx, in, opts...)
}

// 批量删除
func (m *defaultManagerService) ProjectAuditLogBatchDel(ctx context.Context, in *BatchDelOnecProjectAuditLogReq, opts ...grpc.CallOption) (*BatchDelOnecProjectAuditLogResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.ProjectAuditLogBatchDel(ctx, in, opts...)
}

// 删除指定天数之前的数据
func (m *defaultManagerService) ProjectAuditLogDelBeforeDays(ctx context.Context, in *DelOnecProjectAuditLogBeforeDaysReq, opts ...grpc.CallOption) (*DelOnecProjectAuditLogBeforeDaysResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.ProjectAuditLogDelBeforeDays(ctx, in, opts...)
}

func (m *defaultManagerService) SchedulePlanSave(ctx context.Context, in *SaveSchedulePlanReq, opts ...grpc.CallOption) (*SaveSchedulePlanResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.SchedulePlanSave(ctx, in, opts...)
}

func (m *defaultManagerService) SchedulePlanUpdateStatus(ctx context.Context, in *UpdateSchedulePlanStatusReq, opts ...grpc.CallOption) (*UpdateSchedulePlanStatusResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.SchedulePlanUpdateStatus(ctx, in, opts...)
}

// 迁移相关
func (m *defaultManagerService) MigrateWorkspace(ctx context.Context, in *MigrateWorkspaceReq, opts ...grpc.CallOption) (*MigrateWorkspaceResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.MigrateWorkspace(ctx, in, opts...)
}

// 告警仪表盘
func (m *defaultManagerService) AlertDashboardOverview(ctx context.Context, in *GetAlertOverviewReq, opts ...grpc.CallOption) (*GetAlertOverviewResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.AlertDashboardOverview(ctx, in, opts...)
}

// 获取告警级别统计
func (m *defaultManagerService) AlertDashboardSeverityStats(ctx context.Context, in *GetAlertSeverityStatsReq, opts ...grpc.CallOption) (*GetAlertSeverityStatsResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.AlertDashboardSeverityStats(ctx, in, opts...)
}

// 获取告警趋势分析
func (m *defaultManagerService) AlertDashboardTrend(ctx context.Context, in *GetAlertTrendReq, opts ...grpc.CallOption) (*GetAlertTrendResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.AlertDashboardTrend(ctx, in, opts...)
}

// 获取告警维度统计
func (m *defaultManagerService) AlertDashboardDimensionStats(ctx context.Context, in *GetAlertDimensionStatsReq, opts ...grpc.CallOption) (*GetAlertDimensionStatsResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.AlertDashboardDimensionStats(ctx, in, opts...)
}

// 获取告警排行榜
func (m *defaultManagerService) AlertDashboardTopRanking(ctx context.Context, in *GetAlertTopRankingReq, opts ...grpc.CallOption) (*GetAlertTopRankingResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.AlertDashboardTopRanking(ctx, in, opts...)
}

// 获取告警实时状态
func (m *defaultManagerService) AlertDashboardRealtimeStatus(ctx context.Context, in *GetAlertRealtimeStatusReq, opts ...grpc.CallOption) (*GetAlertRealtimeStatusResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.AlertDashboardRealtimeStatus(ctx, in, opts...)
}

// 获取告警汇总报告
func (m *defaultManagerService) AlertDashboardSummaryReport(ctx context.Context, in *GetAlertSummaryReportReq, opts ...grpc.CallOption) (*GetAlertSummaryReportResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.AlertDashboardSummaryReport(ctx, in, opts...)
}

// 集群资源仪表盘
func (m *defaultManagerService) GetResourceDashboardSummary(ctx context.Context, in *ResourceDashboardSummaryReq, opts ...grpc.CallOption) (*ResourceDashboardSummaryResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.GetResourceDashboardSummary(ctx, in, opts...)
}

// 获取集群资源排行
func (m *defaultManagerService) GetClusterResourceRanking(ctx context.Context, in *ClusterResourceRankingReq, opts ...grpc.CallOption) (*ClusterResourceRankingResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.GetClusterResourceRanking(ctx, in, opts...)
}

// 获取项目资源排行
func (m *defaultManagerService) GetProjectResourceRanking(ctx context.Context, in *ProjectResourceRankingReq, opts ...grpc.CallOption) (*ProjectResourceRankingResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.GetProjectResourceRanking(ctx, in, opts...)
}

// 获取工作空间资源排行
func (m *defaultManagerService) GetWorkspaceResourceRanking(ctx context.Context, in *WorkspaceResourceRankingReq, opts ...grpc.CallOption) (*WorkspaceResourceRankingResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.GetWorkspaceResourceRanking(ctx, in, opts...)
}

// -----------------------收费配置表-----------------------
func (m *defaultManagerService) OnecBillingPriceConfigAdd(ctx context.Context, in *OnecBillingPriceConfigAddReq, opts ...grpc.CallOption) (*OnecBillingPriceConfigAddResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.OnecBillingPriceConfigAdd(ctx, in, opts...)
}

func (m *defaultManagerService) OnecBillingPriceConfigUpdate(ctx context.Context, in *OnecBillingPriceConfigUpdateReq, opts ...grpc.CallOption) (*OnecBillingPriceConfigUpdateResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.OnecBillingPriceConfigUpdate(ctx, in, opts...)
}

func (m *defaultManagerService) OnecBillingPriceConfigDel(ctx context.Context, in *OnecBillingPriceConfigDelReq, opts ...grpc.CallOption) (*OnecBillingPriceConfigDelResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.OnecBillingPriceConfigDel(ctx, in, opts...)
}

func (m *defaultManagerService) OnecBillingPriceConfigGetById(ctx context.Context, in *OnecBillingPriceConfigGetByIdReq, opts ...grpc.CallOption) (*OnecBillingPriceConfigGetByIdResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.OnecBillingPriceConfigGetById(ctx, in, opts...)
}

func (m *defaultManagerService) OnecBillingPriceConfigSearch(ctx context.Context, in *OnecBillingPriceConfigSearchReq, opts ...grpc.CallOption) (*OnecBillingPriceConfigSearchResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.OnecBillingPriceConfigSearch(ctx, in, opts...)
}

// -----------------------计费配置绑定表-----------------------
func (m *defaultManagerService) OnecBillingConfigBindingAdd(ctx context.Context, in *OnecBillingConfigBindingAddReq, opts ...grpc.CallOption) (*OnecBillingConfigBindingAddResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.OnecBillingConfigBindingAdd(ctx, in, opts...)
}

func (m *defaultManagerService) OnecBillingConfigBindingUpdate(ctx context.Context, in *OnecBillingConfigBindingUpdateReq, opts ...grpc.CallOption) (*OnecBillingConfigBindingUpdateResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.OnecBillingConfigBindingUpdate(ctx, in, opts...)
}

func (m *defaultManagerService) OnecBillingConfigBindingDel(ctx context.Context, in *OnecBillingConfigBindingDelReq, opts ...grpc.CallOption) (*OnecBillingConfigBindingDelResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.OnecBillingConfigBindingDel(ctx, in, opts...)
}

func (m *defaultManagerService) OnecBillingConfigBindingGet(ctx context.Context, in *OnecBillingConfigBindingGetReq, opts ...grpc.CallOption) (*OnecBillingConfigBindingGetResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.OnecBillingConfigBindingGet(ctx, in, opts...)
}

// -----------------------账单仪表盘-----------------------
func (m *defaultManagerService) OnecBillingDashboardStats(ctx context.Context, in *OnecBillingDashboardStatsReq, opts ...grpc.CallOption) (*OnecBillingDashboardStatsResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.OnecBillingDashboardStats(ctx, in, opts...)
}

func (m *defaultManagerService) OnecBillingCostComposition(ctx context.Context, in *OnecBillingCostCompositionReq, opts ...grpc.CallOption) (*OnecBillingCostCompositionResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.OnecBillingCostComposition(ctx, in, opts...)
}

func (m *defaultManagerService) OnecBillingCostTrend(ctx context.Context, in *OnecBillingCostTrendReq, opts ...grpc.CallOption) (*OnecBillingCostTrendResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.OnecBillingCostTrend(ctx, in, opts...)
}

func (m *defaultManagerService) OnecBillingProjectTop(ctx context.Context, in *OnecBillingProjectTopReq, opts ...grpc.CallOption) (*OnecBillingProjectTopResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.OnecBillingProjectTop(ctx, in, opts...)
}

func (m *defaultManagerService) OnecBillingClusterTop(ctx context.Context, in *OnecBillingClusterTopReq, opts ...grpc.CallOption) (*OnecBillingClusterTopResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.OnecBillingClusterTop(ctx, in, opts...)
}

// -----------------------账单中心-----------------------
func (m *defaultManagerService) OnecBillingStatementSearch(ctx context.Context, in *OnecBillingStatementSearchReq, opts ...grpc.CallOption) (*OnecBillingStatementSearchResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.OnecBillingStatementSearch(ctx, in, opts...)
}

func (m *defaultManagerService) OnecBillingStatementDel(ctx context.Context, in *OnecBillingStatementDelReq, opts ...grpc.CallOption) (*OnecBillingStatementDelResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.OnecBillingStatementDel(ctx, in, opts...)
}

func (m *defaultManagerService) OnecBillingStatementBatchDel(ctx context.Context, in *OnecBillingStatementBatchDelReq, opts ...grpc.CallOption) (*OnecBillingStatementBatchDelResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.OnecBillingStatementBatchDel(ctx, in, opts...)
}

// 立即生成账单
func (m *defaultManagerService) OnecBillingStatementGenerate(ctx context.Context, in *OnecBillingStatementGenerateReq, opts ...grpc.CallOption) (*OnecBillingStatementGenerateResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.OnecBillingStatementGenerate(ctx, in, opts...)
}

// 生成所有账单
func (m *defaultManagerService) OnecBillingStatementGenerateAll(ctx context.Context, in *OnecBillingStatementGenerateAllReq, opts ...grpc.CallOption) (*OnecBillingStatementGenerateAllResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.OnecBillingStatementGenerateAll(ctx, in, opts...)
}

// 获取Alertmanager配置
func (m *defaultManagerService) GetAlertmanagerConfig(ctx context.Context, in *GetAlertmanagerConfigReq, opts ...grpc.CallOption) (*GetAlertmanagerConfigResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.GetAlertmanagerConfig(ctx, in, opts...)
}

// 获取Prometheus配置
func (m *defaultManagerService) GetPrometheusConfig(ctx context.Context, in *GetPrometheusConfigReq, opts ...grpc.CallOption) (*GetPrometheusConfigResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.GetPrometheusConfig(ctx, in, opts...)
}

// 配置Alertmanager
func (m *defaultManagerService) SetAlertmanagerConfig(ctx context.Context, in *SetAlertmanagerConfigReq, opts ...grpc.CallOption) (*SetAlertmanagerConfigResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.SetAlertmanagerConfig(ctx, in, opts...)
}

// 按集群拉取 onec_cluster_node_energy（已删过滤），供工作负载「能耗感知」软偏好
func (m *defaultManagerService) ListOnecClusterNodeEnergy(ctx context.Context, in *ListOnecClusterNodeEnergyReq, opts ...grpc.CallOption) (*ListOnecClusterNodeEnergyResp, error) {
	client := pb.NewManagerServiceClient(m.cli.Conn())
	return client.ListOnecClusterNodeEnergy(ctx, in, opts...)
}
